---
title: "Patient-level data plugins"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Aggregated data plugins}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Dygraph plugin

### Description

- **Version** : 0.0.1
- **Libraries** : dygraphs, xts

### UI code

```{r, eval = FALSE}
temp <- function(){

    ##########################################
    # Translations                           #
    ##########################################
    
    new_words <- tibble::tribble(~language, ~reference_word, ~translated_word,
        "EN", "all_stays", "All stays",
        "FR", "all_stays", "Tous les séjours",
        "EN", "current_stay", "Current stay",
        "FR", "current_stay", "Du séjour sélectionné",
        "EN", "show_data_of", "Show data of",
        "FR", "show_data_of", "Afficher les données de",
        "EN", "show_stays", "Show stays",
        "FR", "show_stays", "Afficher les séjours"
    )

    ##########################################
    # Render UI                              #
    ##########################################

    dygraph_output <- ""
    if (requireNamespace("dygraphs", quietly = TRUE)) dygraph_output <- dygraphs::dygraphOutput(ns("dygraph_%group_id%_%patient_id%"), height = "300px")
    
    options <- list(
        list(key = "all_stays", text = translate(language, "all_stays", new_words)),
        list(key = "current_stay", text = translate(language, "current_stay", new_words))
    )

    div(
        uiOutput(ns("message_bar_1_%group_id%_%patient_id%")),
        uiOutput(ns("message_bar_2_%group_id%_%patient_id%")), br(),
        shiny.fluent::Stack(horizontal = TRUE, tokens = list(childrenGap = 10),
            div(strong(paste0(translate(language, "show_data_of", new_words)), " :"), style = "margin-top:8px;"), 
            shiny.fluent::ChoiceGroup.shinyInput(ns("data_choice_%group_id%_%patient_id%"), value = "all_stays", options = options, className = "inline_choicegroup"),
            div(style = "width:50px;"),
            div(shiny.fluent::Toggle.shinyInput(ns("show_stays_%group_id%_%patient_id%"), value = TRUE), style = "margin-top:8px;"),
            div(strong(paste0(translate(language, "show_stays", new_words))), style = "margin-top:8px;")
        ), br(),
        dygraph_output
    )

}

temp()
```

### Server code

```{r, eval = FALSE}
##########################################
# Translations                           #
##########################################

new_words <- tibble::tribble(~language, ~reference_word, ~translated_word,
    "EN", "dygraphs_required", "Library dygraphs required to display the graph, please install it with install.packages('dygraphs')",
    "FR", "dygraphs_required", "Le package dygraphs est nécessaire pour afficher le graphique, merci de l'installer avec install.packages('dygraphs')",
    "EN", "xts_required", "Library xts required to display the graph, please install it with install.packages('xts')",
    "FR", "xts_required", "Le package xts est nécessaire pour afficher le graphique, merci de l'installer avec install.packages('xts')",
    "EN", "admission", "Admission",
    "FR", "admission", "Admission",
    "EN", "discharge", "Discharge",
    "FR", "discharge", "Discharge"
)

##########################################
# Reload dygraph                         #
##########################################

observeEvent(input$data_choice_%group_id%_%patient_id%, r$reload_%group_id%_%patient_id% <- Sys.time())
observeEvent(input$show_stays_%group_id%_%patient_id%, r$reload_%group_id%_%patient_id% <- Sys.time())

observeEvent(r$reload_%group_id%_%patient_id%, {

    tryCatch({
    
        ##########################################
        # Data processing                        #
        ##########################################

        if (input$data_choice_%group_id%_%patient_id% == "all_stays") data_temp <- data$labs_vitals
        if (input$data_choice_%group_id%_%patient_id% == "current_stay") data_temp <- data$labs_vitals_stay
    
        # Remove duplicates if exist
        # Group by display_name, so if we have multiple identical items from distinct thesaurus, only one legend will appear for both
        
        if (nrow(data_temp) > 0){
            if (requireNamespace("dygraphs", quietly = TRUE) & requireNamespace("xts", quietly = TRUE)){
                data_temp <- 
                    data_temp %>%
                    dplyr::group_by(datetime_start, display_name, value_num) %>%
                    dplyr::slice(1) %>%
                    dplyr::ungroup() %>%
                    dplyr::select(datetime_start, display_name, value_num) %>%
                    dplyr::arrange(datetime_start)
                
                data_temp <- data_temp %>% tidyr::pivot_wider(names_from = display_name, values_from = value_num)
                
                data_temp <- xts::xts(x = data_temp %>% dplyr::select(-datetime_start), order.by = data_temp %>% dplyr::pull(datetime_start))
                
                # Create the dygraph
                data_temp <-
                    dygraphs::dygraph(data_temp) %>%
                    dygraphs::dyAxis("y", valueRange = c(0, max(data_temp, na.rm = T) + max(data_temp, na.rm = T) / 4)) %>%
                    dygraphs::dyAxis("x", drawGrid = FALSE) %>%
                    dygraphs::dyRangeSelector() %>%
                    dygraphs::dyRoller(rollPeriod = 2) %>%
                    dygraphs::dyLegend(show = "always", hideOnMouseOut = TRUE, labelsSeparateLines = T) %>%
                    dygraphs::dyHighlight(highlightCircleSize = 5)
                    
                # Show stays with vertical lines ?
                if (input$show_stays_%group_id%_%patient_id%){
                
                    data_temp <- data_temp %>%
                    dygraphs::dyEvent(data$stays %>% dplyr::pull(admission_datetime),# color = "#5AAE61",
                        label = paste0(data$stays %>% dplyr::pull(unit_name), " - ", translate(language, "admission", new_words)), labelLoc = "bottom") %>%
                    dygraphs::dyEvent(data$stays %>% dplyr::pull(discharge_datetime),# color = "#5AAE61",
                        label = paste0(data$stays %>% dplyr::pull(unit_name), " - ", translate(language, "discharge", new_words)), labelLoc = "bottom")
                } 
                
                data_temp_items <-
                    data$labs_vitals %>%
                    dplyr::group_by(item_id, display_name, colour, unit) %>%
                    dplyr::slice(1) %>%
                    dplyr::ungroup()
                    
                sapply(1:nrow(data_temp_items), function(i){
                    row <- data_temp_items[i, ]
                    data_temp <<- 
                        data_temp %>%
                        dygraphs::dySeries(
                            name = row$display_name, 
                            label = paste0(row$display_name, " (", row$unit, ")"),
                            color = row$colour
                    )
                })
                
                output$dygraph_%group_id%_%patient_id% <- dygraphs::renderDygraph(data_temp)
            }
            
            if (!requireNamespace("dygraphs", quietly = TRUE)) output$message_bar_1_%group_id%_%patient_id% <- renderUI(
                div(shiny.fluent::MessageBar(translate(language, "dygraphs_required", new_words), messageBarType = 3), style = "margin-top:10px;"))
                
            if (!requireNamespace("xts", quietly = TRUE)) output$message_bar_2_%group_id%_%patient_id% <- renderUI(
                div(shiny.fluent::MessageBar(translate(language, "xts_required", new_words), messageBarType = 3), style = "margin-top:10px;"))
        }
        
    },
    error = function(e) if (nchar(e[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", 
        error_name = "%group_id% - run server code", category = "Error", error_report = toString(e), language = language),
    warning = function(w) if (nchar(w[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", 
        error_name = "%group_id% - run server code", category = "Warning", error_report = toString(w), language = language))
})
```

## Datatable plugin

### Description

- **Version** : 0.0.1
- **Libraries** : DT



### UI code

```{r, eval = FALSE}
temp <- function(){

    ##########################################
    # Translations                           #
    ##########################################
    
    new_words <- tibble::tribble(~language, ~reference_word, ~translated_word,
        "EN", "all_stays", "All stays",
        "FR", "all_stays", "Tous les séjours",
        "EN", "current_stay", "Current stay",
        "FR", "current_stay", "Du séjour sélectionné",
        "EN", "show_data_of", "Show data of",
        "FR", "show_data_of", "Afficher les données de",
        "EN", "show_stays", "Show stays",
        "FR", "show_stays", "Afficher les séjours"
    )

    ##########################################
    # Render UI                              #
    ##########################################

    options <- list(
        list(key = "all_stays", text = translate(language, "all_stays", new_words)),
        list(key = "current_stay", text = translate(language, "current_stay", new_words))
    )

    div(
        shiny.fluent::Stack(horizontal = TRUE, tokens = list(childrenGap = 10),
            div(strong(paste0(translate(language, "show_data_of", new_words)), " :"), style = "margin-top:8px;"), 
            shiny.fluent::ChoiceGroup.shinyInput(ns("data_choice_%group_id%_%patient_id%"), value = "all_stays", options = options, className = "inline_choicegroup")
        ), 
        DT::DTOutput(ns("datatable_%group_id%_%patient_id%"))
    )
    
}

temp()
```

### Server code

```{r, eval = FALSE}
##########################################
# Translations                           #
##########################################

new_words <- tibble::tribble(~language, ~reference_word, ~translated_word,
    "EN", "item_name", "Item name",
    "FR", "item_name", "Nom de l'item",
    "EN", "datetime", "Datetime",
    "FR", "datetime", "Date & heure",
    "EN", "value", "Value",
    "FR", "value", "Valeur",
    "EN", "unit", "Unit",
    "FR", "unit", "Unité"
)

##########################################
# Reload datatable                       #
##########################################

observeEvent(input$data_choice_%group_id%_%patient_id%, r$reload_%group_id%_%patient_id% <- Sys.time())

observeEvent(r$reload_%group_id%_%patient_id%, {

    tryCatch({

        ##########################################
        # Data preprocessing                     #
        ##########################################
        
        if (input$data_choice_%group_id%_%patient_id% == "all_stays") data_temp <- data$labs_vitals
        if (input$data_choice_%group_id%_%patient_id% == "current_stay") data_temp <- data$labs_vitals_stay

        data_temp <-
            data_temp %>%
            dplyr::select(display_name, value_num, unit, datetime_start) %>%
            dplyr::mutate_at("datetime_start", as.character)
            
        ##########################################
        # Render datatable                       #
        ##########################################
        
        col_names <- c(translate(language, "item_name", new_words), translate(language, "value", new_words), translate(language, "unit", new_words), 
            translate(language, "datetime", new_words))
            
        sortable_cols <- c("display_name", "datetime_start", "value_num")
        centered_cols <- c("datetime_start", "unit")
        column_widths = c("datetime_start" = "180px", "value_num" = "150px", "unit" = "100px")
        searchable_cols <- c("display_name", "datetime_start", "value_num")
        factorize_cols <- c("display_name")
        
        render_datatable(
            data = data_temp,
            output = output,
            r = r,
            ns = ns,
            language = language,
            output_name = "datatable_%group_id%_%patient_id%",
            col_names = col_names,
            page_length = 10,
            sortable_cols = sortable_cols,
            centered_cols = centered_cols,
            column_widths = column_widths,
            filter = TRUE,
            searchable_cols = searchable_cols,
            factorize_cols = factorize_cols
        )
        
    },
    error = function(e) if (nchar(e[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", 
        error_name = "%group_id% - run server code", category = "Error", error_report = toString(e), language = language),
    warning = function(w) if (nchar(w[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", 
        error_name = "%group_id% - run server code", category = "Warning", error_report = toString(w), language = language))
})
```

## Text plugin

### Description

- **Version** : 0.0.1
- **Libraries** : none

### UI code

```{r, eval = FALSE}
temp <- function(){

    ##########################################
    # Translations                           #
    ##########################################
    
    new_words <- tibble::tribble(~language, ~reference_word, ~translated_word,
        "EN", "all_stays", "All stays",
        "FR", "all_stays", "Tous les séjours",
        "EN", "current_stay", "Current stay",
        "FR", "current_stay", "Du séjour sélectionné",
        "EN", "show_data_of", "Show data of",
        "FR", "show_data_of", "Afficher les données de",
        "EN", "search_text", "Search text",
        "FR", "search_text", "Recherche de texte",
        "EN", "manage_words_sets", "Manage words sets",
        "FR", "manage_words_sets", "Gérer les sets de mots",
        "EN", "words_set", "Words set",
        "FR", "words_set", "Set de mots",
        "EN", "new_words_set", "New words set",
        "FR", "new_words_set", "Nouveau set de mots",
        "EN", "delete_words_set", "Delete a words set",
        "FR", "delete_words_set", "Supprimer un set de mots",
        "EN", "add_remove_words", "Add or remove words",
        "FR", "add_remove_words", "Ajouter ou supprimer des mots",
        "EN", "words", "Words",
        "FR", "words", "Mots"
    )
    
    ##########################################
    # Render UI                              #
    ##########################################
    
    options_text_choice <- list(
        list(key = "search_text", text = translate(language, "search_text", new_words)),
        list(key = "manage_words_sets", text = translate(language, "manage_words_sets", new_words)))
    
    options <- list(
        list(key = "all_stays", text = translate(language, "all_stays", new_words)),
        list(key = "current_stay", text = translate(language, "current_stay", new_words)))
        
    options_words_set <- convert_tibble_to_list(DBI::dbGetQuery(r$db, "SELECT * FROM modules_elements_options WHERE deleted IS FALSE 
        AND group_id = %group_id% AND patient_id = %patient_id% AND name = 'words_set_name'"), key_col = "id", text_col = "value")
    
    div(
        shiny.fluent::Stack(horizontal = TRUE, tokens = list(childrenGap = 10),
            shiny.fluent::ChoiceGroup.shinyInput(ns("text_choice_%group_id%_%patient_id%"), value = "search_text", options = options_text_choice, className = "inline_choicegroup"),
            div(style = "width:50px;"),
            div(strong(paste0(translate(language, "show_data_of", new_words)), " :"), style = "margin-top:8px;"), 
            shiny.fluent::ChoiceGroup.shinyInput(ns("data_choice_%group_id%_%patient_id%"), value = "all_stays", options = options, className = "inline_choicegroup")
        ),
        
        conditionalPanel(condition = "input.text_choice_%group_id%_%patient_id% == 'search_text'", ns = ns,
            make_dropdown(label = "words_set", id = "select_words_set_%group_id%_%patient_id%", ns = ns, options = options_words_set, width = "300px", words = new_words),
            uiOutput(ns("text_%group_id%_%patient_id%"))
        ),
        
        conditionalPanel(condition = "input.text_choice_%group_id%_%patient_id% == 'manage_words_sets'", ns = ns,
            br(), shiny.fluent::Text(variant = "large", translate(language, "add_remove_words", new_words), block = TRUE),
            shiny.fluent::Stack(horizontal = TRUE, tokens = list(childrenGap = 20),
                make_dropdown(label = "words_set", id = "manage_words_set_%group_id%_%patient_id%", ns = ns, options = options_words_set, width = "300px", words = new_words),
                make_dropdown(label = "words", id = "manage_words_%group_id%_%patient_id%", ns = ns, width = "300px", words = new_words, multiSelect = TRUE),
                div(shiny.fluent::DefaultButton.shinyInput(ns("manage_words_save_%group_id%_%patient_id%"), translate(language, "save", r$words)), style = "padding-top:38px;")
            ),
            shiny.fluent::Stack(horizontal = TRUE, tokens = list(childrenGap = 20),
                make_textfield(label = "name", id = "manage_words_add_name_%group_id%_%patient_id%", ns = ns, width = "300px"),
                div(shiny.fluent::PrimaryButton.shinyInput(ns("manage_words_add_%group_id%_%patient_id%"), translate(language, "add", r$words)), style = "padding-top:38px;")
            ),
            br(), hr(), shiny.fluent::Text(variant = "large", translate(language, "new_words_set", new_words), block = TRUE),
            shiny.fluent::Stack(horizontal = TRUE, tokens = list(childrenGap = 20),
                make_textfield(label = "name", id = "new_words_set_name_%group_id%_%patient_id%", ns = ns, width = "300px"),
                div(shiny.fluent::PrimaryButton.shinyInput(ns("new_words_set_add_%group_id%_%patient_id%"), translate(language, "add", r$words)), style = "padding-top:38px;")
            ),
            br(), hr(), shiny.fluent::Text(variant = "large", translate(language, "delete_words_set", new_words), block = TRUE),
            shiny.fluent::Stack(horizontal = TRUE, tokens = list(childrenGap = 20),
                make_dropdown(label = "words_set", id = "delete_words_set_%group_id%_%patient_id%", ns = ns, options = options_words_set, width = "300px", words = new_words),
                div(shiny.fluent::DefaultButton.shinyInput(ns("delete_words_set_validate_%group_id%_%patient_id%"), translate(language, "delete", r$words)), style = "padding-top:38px;")
            )
        )
    )
    
}

temp()
```

### Server code

```{r, eval = FALSE}
##########################################
# Translations                           #
##########################################

new_words <- tibble::tribble(~language, ~reference_word, ~translated_word,
    "EN", "new_words_set_added", "New words set added",
    "FR", "new_words_set_added", "Nouveau set de mots ajouté",
    "EN", "delete_words_set", "Delete a words set",
    "FR", "delete_words_set", "Supprimer un set de mots",
    "EN", "delete_words_set_subtext", "Are you sure you want to delete this words set ?",
    "FR", "delete_words_set_subtext", "Etes-vous sûr de vouloir supprimer ce set de mots ?",
    "EN", "words_set_deleted", "Words set deleted",
    "FR", "words_set_deleted", "Set de mots supprimé"
)

##########################################
# Add a new words set                    #
##########################################

observeEvent(input$new_words_set_add_%group_id%_%patient_id%, {

    tryCatch({
    
        new_name <- input$new_words_set_name_%group_id%_%patient_id%
        
        if (length(new_name) == 0) shiny.fluent::updateTextField.shinyInput(session, "new_words_set_name_%group_id%_%patient_id%", errorMessage = translate(language, paste0("provide_valid_name"), r$words))
        else shiny.fluent::updateTextField.shinyInput(session, "new_words_set_name_%group_id%_%patient_id%", errorMessage = NULL)
        
        req(length(new_name) > 0)
        
        sql <- "SELECT DISTINCT(value) FROM modules_elements_options WHERE deleted IS FALSE AND group_id = %group_id% AND patient_id = %patient_id% AND name = 'words_set_name'" 
        distinct_values <- DBI::dbGetQuery(r$db, sql) %>% dplyr::pull() %>% tolower()
          
        if (tolower(new_name) %in% distinct_values) show_message_bar(output, 2, "name_already_used", "severeWarning", language)
        req(tolower(new_name) %not_in% distinct_values)
        
        last_row <- get_last_row(r$db, "modules_elements_options")
        
        # Insert new words_set in database
        
        sql <- glue::glue_sql("INSERT INTO modules_elements_options(id, group_id, patient_id, category, name, value, creator_id, datetime, deleted)
            SELECT {last_row + 1}, %group_id%, %patient_id%, 'aggregated', 'words_set_name', {new_name}, {r$user_id}, {as.character(Sys.time())}, FALSE", .con = r$db)
        query <- DBI::dbSendStatement(r$db, sql)
        DBI::dbClearResult(query)
        
        # Reset textfield
        shiny.fluent::updateTextField.shinyInput(session, "new_words_set_name_%group_id%_%patient_id%", value = NULL)
        
        # Update dropdowns
        r$reload_%group_id%_%patient_id% <- Sys.time()
        
        show_message_bar(output, 1, translate(language, "new_words_set_added", new_words), "success", language)
    
    },
    error = function(e) if (nchar(e[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", error_name = "%group_id% - run server code", category = "Error", error_report = toString(e), language = language))
})

##########################################
# Delete a words set                     #
##########################################

# Delete button is pressed
observeEvent(input$delete_words_set_validate_%group_id%_%patient_id%, r$delete_dialog_%group_id%_%patient_id% <- TRUE)

# Rendering react output
observeEvent(r$delete_dialog_%group_id%_%patient_id% , {
    output$delete_confirm <- shiny.fluent::renderReact({
        dialogContentProps <- list(
            type = 0,
            title = translate(language, "delete_words_set", new_words),
            closeButtonAriaLabel = "Close",
            subText = translate(language, "delete_words_set_subtext", new_words)
        )
        shiny.fluent::Dialog(
            hidden = !r$delete_dialog_%group_id%_%patient_id%,
            onDismiss = htmlwidgets::JS(paste0("function() { Shiny.setInputValue('hide_dialog_%group_id%_%patient_id%', Math.random()); }")),
            dialogContentProps = dialogContentProps,
            modalProps = list(),
            shiny.fluent::DialogFooter(
                shiny.fluent::PrimaryButton.shinyInput(ns("delete_confirmed_%group_id%_%patient_id%"), text = translate(language, "delete", r$words)),
                shiny.fluent::DefaultButton.shinyInput(ns("delete_canceled_%group_id%_%patient_id%"), text = translate(language, "dont_delete", r$words))
            )
        )
    })
})

# Whether to close or not delete dialog box
observeEvent(input$hide_dialog_%group_id%_%patient_id%, r$delete_dialog_%group_id%_%patient_id% <- FALSE)
observeEvent(input$delete_canceled_%group_id%_%patient_id%, r$delete_dialog_%group_id%_%patient_id% <- FALSE)

# When the delete is confirmed
observeEvent(input$delete_confirmed_%group_id%_%patient_id%, {

    tryCatch({
        
        # Get value of deleted row
        row_deleted <- as.integer(input$delete_words_set_%group_id%_%patient_id%)
        
        # Delete row in database
        sql <- glue::glue_sql("UPDATE modules_elements_options SET deleted = TRUE WHERE id = {row_deleted} OR link_id = {row_deleted}", .con = r$db)
        query <- DBI::dbSendStatement(r$db, sql)
        DBI::dbClearResult(query)
        
        # Close dialog box
        r$delete_dialog_%group_id%_%patient_id% <- FALSE
        
        # Notification to user
        show_message_bar(output = output, id = 3, translate(language, "words_set_deleted", new_words), type = "severeWarning", language = language)
        
        r$reload_%group_id%_%patient_id% <- Sys.time()

    },
    error = function(e) if (nchar(e[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", error_name = "%group_id% - run server code", category = "Error", error_report = toString(e), language = language))
})

##########################################
# Load words of a words set              #
##########################################

observeEvent(input$manage_words_set_%group_id%_%patient_id%, {

    tryCatch({
    
        sql <- glue::glue_sql("SELECT * FROM modules_elements_options WHERE deleted IS FALSE AND group_id = %group_id% AND patient_id = %patient_id%
            AND name = 'words_set_word' AND link_id = {input$manage_words_set_%group_id%_%patient_id%}", .con = r$db)
        
        r$words_%group_id%_%patient_id% <- DBI::dbGetQuery(r$db, sql) %>% dplyr::select(value)
        
        shiny.fluent::updateDropdown.shinyInput(session, "manage_words_%group_id%_%patient_id%", 
            options = convert_tibble_to_list(data = r$words_%group_id%_%patient_id%, key_col = "value", text_col = "value", null_value = FALSE),
            value = r$words_%group_id%_%patient_id% %>% dplyr::pull(value))
    },
    error = function(e) if (nchar(e[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", error_name = "%group_id% - run server code", category = "Error", error_report = toString(e), language = language))
})

##########################################
# Update words in a words set            #
##########################################

observeEvent(input$manage_words_%group_id%_%patient_id%, {

    tryCatch({
    
        # Update r var ...
    },
    error = function(e) if (nchar(e[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", error_name = "%group_id% - run server code", category = "Error", error_report = toString(e), language = language)) 
})

##########################################
# Add a new word                         #
##########################################

observeEvent(input$manage_words_add_%group_id%_%patient_id%, {
    
    tryCatch({
    
        r$words_%group_id%_%patient_id% <- r$words_%group_id%_%patient_id% %>% dplyr::bind_rows(tibble::tribble(~value, input$manage_words_add_name_%group_id%_%patient_id%))
        
        shiny.fluent::updateDropdown.shinyInput(session, "manage_words_%group_id%_%patient_id%", 
            options = convert_tibble_to_list(data = r$words_%group_id%_%patient_id%, key_col = "value", text_col = "value", null_value = FALSE),
            value = r$words_%group_id%_%patient_id% %>% dplyr::pull(value))
    },
    error = function(e) if (nchar(e[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", error_name = "%group_id% - run server code", category = "Error", error_report = toString(e), language = language))  
})

##########################################
# Save words of a words set              #
##########################################

observeEvent(input$manage_words_save_%group_id%_%patient_id%, {

    tryCatch({
        
        
    },
    error = function(e) if (nchar(e[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", error_name = "%group_id% - run server code", category = "Error", error_report = toString(e), language = language))
})

##########################################
# Reload data                            #
##########################################

observeEvent(r$reload_%group_id%_%patient_id%, {

    tryCatch({
    
    # Update dropdowns
    
        options <- convert_tibble_to_list(DBI::dbGetQuery(r$db, "SELECT * FROM modules_elements_options WHERE deleted IS FALSE AND group_id = %group_id% AND patient_id = %patient_id% AND name = 'words_set_name'"), key_col = "id", text_col = "value")
        shiny.fluent::updateDropdown.shinyInput(session, "select_words_set_%group_id%_%patient_id%", options = options)
        shiny.fluent::updateDropdown.shinyInput(session, "manage_words_set_%group_id%_%patient_id%", options = options)
        shiny.fluent::updateDropdown.shinyInput(session, "delete_words_set_%group_id%_%patient_id%", options = options)
        
        },
    error = function(e) if (nchar(e[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", error_name = "%group_id% - run server code", category = "Error", error_report = toString(e), language = language))
})

##########################################
# Get results for search & sets          #
##########################################



##########################################
# Load & render text                     #
##########################################

observeEvent(input$data_choice_%group_id%_%patient_id%, r$reload_%group_id%_%patient_id% <- Sys.time())

observeEvent(r$reload_%group_id%_%patient_id%, {

    output$text_%group_id%_%patient_id% <- renderUI({
    
        tryCatch({
            
            result <- tagList()
            
            if (input$data_choice_%group_id%_%patient_id% == "all_stays") data_temp <- data$text
            if (input$data_choice_%group_id%_%patient_id% == "current_stay") data_temp <- data$text_stay
            
            if (nrow(data_temp) > 0){
                data_temp <- data_temp %>% dplyr::arrange(desc(datetime_start))
            
                sapply(1:nrow(data_temp), function(i){
                    row <- data_temp[i, ]
                    result <<- tagList(result, br(),
                        div(
                            strong(paste0(row$datetime_start, " - ", row$display_name)), br(), br(),
                            HTML(row$value %>% stringr::str_replace_all("\n", "<br />")),
                            style = "border: dashed 1px; padding: 10px"
                        ),
                    )
                })
            }
            
            if (nrow(data_temp) == 0) result <- div(shiny.fluent::MessageBar(translate(language, "DT_empty", r$words), messageBarType = 0), style = "margin-top:10px;")
        
            result
        
        },
        error = function(e) if (nchar(e[1]) > 0) report_bug(r = r, output = output, error_message = "error_run_plugin_server_code", error_name = "%group_id% - run server code", category = "Error", error_report = toString(e), language = language))
    })
})
```

## Vistime

### Description

- **Version** : 0.0.1
- **Libraries** : none

### UI code

```{r, eval = FALSE}

```

### Server code

```{r, eval = FALSE}

```