#' Translate a word
#'
#' @param language A two-letters or three-letters character indicating the requested language
#' @param words A tibble containing the translations
#' @description Translates a reference word to the requested language
#'
#' @return Returns the translated word (character)
#' @examples
#' words <- dplyr::tribble(~language, ~reference_word, ~translated_word,
#' "FR", "settings", "Parametres",
#' "IT", "settings", "Impostazioni")
#' 
#' cdwtools::translate("IT", words, "settings")
#' cdwtools::translate("FR", words, "settings")

translate <- function(language, reference_word){
  words <- get_translations()
  if (nchar(language) %not_in% c(2, 3)) stop("Input 'language' has less than 2 or more than 3 characters")
  if (!is.data.frame(words)) stop("Input 'words' is not a dataframe")
  if (!is.character(reference_word) | nchar(reference_word) == 0) stop("Input 'reference word' is not a character or is of length 0")
  
  # return empty word if doesn't exist
  words %>%
    dplyr::filter(language == !!language, reference_word == !!reference_word) %>%
    dplyr::pull(translated_word) -> result
  if (length(result) == 0) result <- ""
  result
}

#' Create a tibble with translations
#'@noRd
#'

get_translations <- function(){
  needed_file <- "./data/translations.csv"
  # if (!file.exists(needed_file)){
    dplyr::tribble(~language, ~reference_word, ~translated_word,
            "EN", "blank", "",
            "FR", "blank", "",
            "EN", "home", "Home",
            "FR", "home", "Accueil",
            "EN", "patient_level_data", "Patient-level data",
            "FR", "patient_level_data", "Données individuelles",
            "EN", "aggregated_data", "Aggregated data",
            "FR", "aggregated_data", "Données agrégées",
            "EN", "settings", "Settings",
            "FR", "settings", "Paramètres",
            "EN", "help", "Help",
            "FR", "help", "Aide",
            "EN", "datamart", "Datamart",
            "FR", "datamart", "Datamart",
            "EN", "datamarts", "Datamarts",
            "FR", "datamarts", "Datamarts",
            "EN", "datamarts_create", "Create a datamart",
            "FR", "datamarts_create", "Créer un datamart",
            "EN", "datamarts_creation_card", "Create a datamart",
            "FR", "datamarts_creation_card", "Créer un datamart",
            "EN", "datamarts_management", "Datamarts management",
            "FR", "datamarts_management", "Gestion des datamarts",
            "EN", "datamarts_datatable_card", "Datamarts management",
            "FR", "datamarts_datatable_card", "Gestion des datamarts",
            "EN", "datamarts_access", "Datamarts access",
            "FR", "datamarts_access", "Accès aux datamarts",
            "EN", "datamart_options", "Datamart options",
            "FR", "datamart_options", "Paramètres du datamart",
            "EN", "datamarts_options_card", "Edit datamarts options",
            "FR", "datamarts_options_card", "Paramètres du datamart",
            "EN", "datamarts_edit_code_card", "Edit code",
            "FR", "datamarts_edit_code_card", "Editer le code",
            "EN", "datamart_access_choice", "Datamart",
            "FR", "datamart_access_choice", "Datamart",
            "EN", "datamart_access_people", "Grant access to",
            "FR", "datamart_access_people", "Permettre l'accès à",
            "EN", "datamarts_studies", "Datamarts & studies",
            "FR", "datamarts_studies", "Datamarts & études",
            "EN", "study_accesses", "Studies accesses",
            "FR", "study_accesses", "Accès aux études",
            "EN", "studies_access_choice", "Study",
            "FR", "studies_access_choice", "Etude",
            "EN", "studies_access_people", "Grant access to",
            "FR", "studies_access_people", "Permettre l'accès à",
            "EN", "study_options", "Study options",
            "FR", "study_options", "Paramètres de l'étude",
            "EN", "studies_management_choice", "Study",
            "FR", "studies_management_choice", "Etude",
            "EN", "thesaurus_options", "Thesaurus options",
            "FR", "thesaurus_options", "Paramètres du thésaurus",
            "EN", "patient_lvl_module_family", "Patient-level data module family",
            "FR", "patient_lvl_module_family", "Données individuelles - groupe de modules",
            "EN", "aggregated_module_family", "Aggregated data module family",
            "FR", "aggregated_module_family", "Données agrégées - groupe de modules",
            "EN", "patient_lvl_module_family_id", "Patient-lvl data module family ID",
            "FR", "patient_lvl_module_family_id", "Données indiv. - ID groupe de modules",
            "EN", "aggregated_module_family_id", "Aggregated data module family ID",
            "FR", "aggregated_module_family_id", "Données agg. - ID groupe de modules",
            "EN", "patient_lvl_module_added", "Module added",
            "FR", "patient_lvl_module_added", "Module ajouté",
            "EN", "patient_lvl_module_family_added", "Module family added",
            "FR", "patient_lvl_module_family_added", "Groupe de modules ajouté",
            "EN", "patient_lvl_module_element_added", "Module element added",
            "FR", "patient_lvl_module_element_added", "Figure ajoutée",
            "EN", "aggregated_module_added", "Module added",
            "FR", "aggregated_module_added", "Module ajouté",
            "EN", "aggregated_module_family_added", "Module family added",
            "FR", "aggregated_module_family_added", "Groupe de modules ajouté",
            "EN", "study", "Study",
            "FR", "study", "Etude",
            "EN", "studies", "Studies",
            "FR", "studies", "Etudes",
            "EN", "subset", "Subset",
            "FR", "subset", "Subset",
            "EN", "subsets", "Subsets",
            "FR", "subsets", "Subsets",
            "EN", "thesaurus", "Thesaurus",
            "FR", "thesaurus", "Thesaurus",
            "EN", "patient", "Patient",
            "FR", "patient", "Patient",
            "EN", "stay", "Stay",
            "FR", "stay", "Séjour",
            "EN", "general", "General",
            "FR", "general", "Général",
            "EN", "general_settings", "General settings",
            "FR", "general_settings", "Paramètres généraux",
            "EN", "data_management", "Data management",
            "FR", "data_management", "Gestion des données",
            "EN", "data_sources", "Data sources",
            "FR", "data_sources", "Sources de données",
            "EN", "data_source", "Data source",
            "FR", "data_source", "Source de données",
            "EN", "create_data_source", "Create a data source",
            "FR", "create_data_source", "Créer une source de données",
            "EN", "data_sources_creation_card", "Create a data source",
            "FR", "data_sources_creation_card", "Créer une source de données",
            "EN", "create_datamart", "Create a datamart",
            "FR", "create_datamart", "Créer un datamart",
            "EN", "create_study", "Create a study",
            "FR", "create_study", "Créer une étude",
            "EN", "create_subset", "Create a subset",
            "FR", "create_subset", "Créer un subset",
            "EN", "create_thesaurus", "Create a thesaurus",
            "FR", "create_thesaurus", "Créer un thésaurus",
            "EN", "name", "Name",
            "FR", "name", "Nom",
            "EN", "description", "Description",
            "FR", "description", "Description",
            "EN", "language", "Language",
            "FR", "language", "Langue",
            "EN", "save", "Save",
            "FR", "save", "Sauvegarder",
            "EN", "edit_save", "Save",
            "FR", "edit_save", "Sauvegarder",
            "EN", "execute_code", "Run code",
            "FR", "execute_code", "Exécuter",
            "EN", "datatable_save", "Save",
            "FR", "datatable_save", "Sauvegarder",
            "EN", "appearance", "Appearance",
            "FR", "appearance", "Apparence",
            "EN", "my_account", "My account",
            "FR", "my_account", "Mon compte",
            "EN", "page_type", "Page type",
            "FR", "page_type", "Type de page",
            "EN", "plugins_modules", "Plugins & modules",
            "FR", "plugins_modules", "Plugins & modules",
            "EN", "plugins", "Plugins",
            "FR", "plugins", "Plugins",
            "EN", "plugin", "Plugin",
            "FR", "plugin", "Plugin",
            "EN", "modules_patient_lvl", "Modules patient-level data",
            "FR", "modules_patient_lvl", "Modules données individuelles",
            "EN", "modules_aggregated", "Modules aggregated data",
            "FR", "modules_aggregated", "Modules données agrégées",
            "EN", "dev_mode", "Developper mode",
            "FR", "dev_mode", "Mode développeur",
            "EN", "search", "Search",
            "FR", "search", "Rechercher",
            "EN", "choices", "Choices",
            "FR", "choices", "Choix",
            "EN", "code", "Code",
            "FR", "code", "Code",
            "EN", "page_theme", "Theme",
            "FR", "page_theme", "Thème",
            "EN", "messages", "Messages",
            "FR", "messages", "Messages",
            "EN", "disconnect", "Disconnect",
            "FR", "disconnect", "Déconnexion",
            "EN", "users", "Users",
            "FR", "users", "Utilisateurs",
            "EN", "log", "Log",
            "FR", "log", "Historique",
            "EN", "app_db", "App database",
            "FR", "app_db", "BDD de l'application",
            "EN", "failed_connect_distant_db", "Failed to connect to distant database",
            "FR", "failed_connect_distant_db", "Echec lors de la connexion à la base de données distante",
            "EN", "error_insert_distant_db_info", "Error inserting distant DB info in local database",
            "FR", "error_insert_distant_db_info", "Erreur lors de l'insertion des données de connexion distante à la BDD dans la BDD locale",
            "EN", "connection_infos", "Connection informations",
            "FR", "connection_infos", "Informations de connexion",
            "EN", "app_db_request", "Request database",
            "FR", "app_db_request", "Requêter la BDD",
            "EN", "request", "Request",
            "FR", "request", "Requêter",
            "EN", "app_db_tables", "Database tables",
            "FR", "app_db_tables", "Tables de la BDD",
            "EN", "db_connexion_type", "Connexion type",
            "FR", "db_connexion_type", "Type de connexion",
            "EN", "local", "Local",
            "FR", "local", "Locale",
            "EN", "distant", "Distant",
            "FR", "distant", "Distante",
            "EN", "dbname", "Database name",
            "FR", "dbname", "Nom de la BDD",
            "EN", "host", "Host",
            "FR", "host", "Hôte",
            "EN", "port", "Port",
            "FR", "port", "Port",
            "EN", "user", "User",
            "FR", "user", "Utilisateur",
            "EN", "password", "Password",
            "FR", "password", "Password",
            "EN", "export_db", "Export database",
            "FR", "export_db", "Exporter la base de données",
            "EN", "restore_db", "Restore database",
            "FR", "restore_db", "Restaurer la base de données",
            "EN", "change_password_card", "Change password",
            "FR", "change_password_card", "Changer mdp",
            "EN", "change_password", "Change password",
            "FR", "change_password", "Changer mdp",
            "EN", "password_changed", "Password updated",
            "FR", "password_changed", "Mot de passe modifié",
            "EN", "old_password", "Old password",
            "FR", "old_password", "Ancien mot de passe",
            "EN", "new_password", "New password",
            "FR", "new_password", "Nouveau mot de passe",
            "EN", "passwords_are_different", "The new passwords are not the same",
            "FR", "passwords_are_different", "Nouveaux mdp non identiques",
            "EN", "invalid_old_password", "Invalid old password",
            "FR", "invalid_old_password", "Ancien mot de passe non valide",
            "EN", "username", "Username",
            "FR", "username", "Pseudo",
            "EN", "create_user", "Create a new user",
            "FR", "create_user", "Créer un nouvel utilisateur",
            "EN", "firstname", "First name",
            "FR", "firstname", "Prénom",
            "EN", "lastname", "Last name",
            "FR", "lastname", "Nom",
            "EN", "add", "Add",
            "FR", "add", "Ajouter",
            "EN", "remove", "Remove",
            "FR", "remove", "Retirer",
            "EN", "reset", "Reset",
            "FR", "reset", "Remettre à zéro",
            "EN", "test_connection", "Test connection",
            "FR", "test_connection", "Tester la connexion",
            "EN", "user_access", "User access",
            "FR", "user_access", "Droits d'accès",
            "EN", "user_status", "User status",
            "FR", "user_status", "Statut de l'utilisateur",
            "EN", "user_management", "User management",
            "FR", "user_management", "Gestion des utilisateurs",
            "EN", "get_started", "Get started",
            "FR", "get_started", "Mise en place",
            "EN", "data_sources_create", "Create a data source",
            "FR", "data_sources_create", "Créer une source de données",
            "EN", "data_sources_management", "Data sources management",
            "FR", "data_sources_management", "Gestion des sources de données",
            "EN", "data_sources_datatable_card", "Data management",
            "FR", "data_sources_datatable_card", "Gestion des données",
            "EN", "studies_create", "Create a study",
            "FR", "studies_create", "Créer une étude",
            "EN", "studies_creation_card", "Create a study",
            "FR", "studies_creation_card", "Créer une étude",
            "EN", "studies_management", "Studies management",
            "FR", "studies_management", "Gestion des études",
            "EN", "studies_datatable_card", "Studies management",
            "FR", "studies_datatable_card", "Gestion des études",
            "EN", "studies_options_card", "Studies options",
            "FR", "studies_options_card", "Paramètres des études",
            "EN", "subsets_create", "Create subset",
            "FR", "subsets_create", "Créer un subset",
            "EN", "subsets_creation_card", "Create subset",
            "FR", "subsets_creation_card", "Créer un subset",
            "EN", "subsets_management", "Subsets management",
            "FR", "subsets_management", "Gestion des subsets",
            "EN", "subsets_datatable_card", "Subsets management",
            "FR", "subsets_datatable_card", "Gestion des subsets",
            "EN", "subsets_edit_code_card", "Edit subset code",
            "FR", "subsets_edit_code_card", "Editer le code",
            "EN", "thesaurus_create", "Create a thesaurus",
            "FR", "thesaurus_create", "Créer un thésaurus",
            "EN", "thesaurus_creation_card", "Create a thesaurus",
            "FR", "thesaurus_creation_card", "Créer un thésaurus",
            "EN", "thesaurus_management", "Thesaurus management",
            "FR", "thesaurus_management", "Gestion des thésaurus",
            "EN", "thesaurus_datatable_card", "Thesaurus management",
            "FR", "thesaurus_datatable_card", "Gestion des thésaurus",
            "EN", "thesaurus_sub_datatable_card", "Thesaurus items management",
            "FR", "thesaurus_sub_datatable_card", "Gestion des items des thésaurus",
            "EN", "thesaurus_management_card", "Thesaurus management",
            "FR", "thesaurus_management_card", "Gestion des thésaurus",
            "EN", "thesaurus_edit_code_card", "Edit thesaurus code",
            "FR", "thesaurus_edit_code_card", "Editer le code",
            "EN", "thesaurus_items", "Items",
            "FR", "thesaurus_items", "Items",
            "EN", "item_colour", "Item colour",
            "FR", "item_colour", "Couleur de l'item",
            "EN", "thesaurus_selected_items", "Items selected",
            "FR", "thesaurus_selected_items", "Items sélectionnés",
            "EN", "thesaurus_items_management_card", "Items management",
            "FR", "thesaurus_items_management_card", "Items des thésaurus",
            "EN", "thesaurus_items_management", "Items management",
            "FR", "thesaurus_items_management", "Gestion des items",
            "EN", "matching_people", "Matching people",
            "FR", "matching_people", "Personnes correspondant",
            "EN", "no_results_found", "No results found",
            "FR", "no_results_found", "Pas de résultats",
            "EN", "module", "Module",
            "FR", "module", "Module",
            "EN", "modules", "Modules",
            "FR", "modules", "Modules",
            "EN", "module_name", "Name of the module",
            "FR", "module_name", "Nom du module",
            "EN", "parent_module", "Parent module",
            "FR", "parent_module", "Est sous le module",
            "EN", "module_family", "Module family",
            "FR", "module_family", "Appartient au groupe de modules",
            "EN", "module_families", "Module families",
            "FR", "module_families", "Familles de modules",
            "EN", "module_access_type", "Grant access",
            "FR", "module_access_type", "Permettre l'accès",
            "EN", "module_access_people", "Grant access to",
            "FR", "module_access_people", "Donner l'accès à",
            "EN", "parent_module_is_itself", "A module can't be its own parent",
            "FR", "parent_module_is_itself", "Un module ne peut être son propre parent",
            "EN", "log_filters", "Log filters",
            "FR", "log_filters", "Filtrer l'historique",
            "EN", "log_details", "Log details",
            "FR", "log_details", "Détails de l'historique",
            "EN", "log_filter_type", "Filter log of",
            "FR", "log_filter_type", "Montrer l'historique de",
            "EN", "log_filter_people", "Users",
            "FR", "log_filter_people", "Utilisateurs",
            "EN", "modif_saved", "Modifications saved",
            "FR", "modif_saved", "Modifications enregistrées",
            "EN", "data_source_deleted", "Data source deleted",
            "FR", "data_source_deleted", "Source de données supprimée",
            "EN", "datamart_deleted", "Datamart deleted",
            "FR", "datamart_deleted", "Datamart supprimé",
            "EN", "study_deleted", "Study deleted",
            "FR", "study_deleted", "Etude",
            "EN", "subset_deleted", "Subset deleted",
            "FR", "subset_deleted", "Subset supprimé",
            "EN", "thesaurus_deleted", "Thesaurus deleted",
            "FR", "thesaurus_deleted", "Thésaurus supprimé",
            "EN", "thesaurus_item_deleted", "Thesaurus item deleted",
            "FR", "thesaurus_item_deleted", "Item de thésaurus supprimé",
            "EN", "data_source_added", "New data source added",
            "FR", "data_source_added", "Nouvelle source de données ajoutée",
            "EN", "datamart_added", "New datamart added",
            "FR", "datamart_added", "Nouveau datamart ajouté",
            "EN", "study_added", "New study added",
            "FR", "study_added", "Nouvelle étude ajoutée",
            "EN", "subset_added", "New subset added",
            "FR", "subset_added", "Nouveau subset ajouté",
            "EN", "thesaurus_added", "Thesaurus created",
            "FR", "thesaurus_added", "Thésaurus crée",
            "EN", "data_sources_delete", "Delete a data source",
            "FR", "data_sources_delete", "Supprimer une source de donnée",
            "EN", "data_sources_delete_subtext", "Do you want yo delete this data source ?",
            "FR", "data_sources_delete_subtext", "Confirmez-vous la suppression de cette source de données ?",
            "EN", "modules_delete", "Delete a module",
            "FR", "modules_delete", "Supprimer un module",
            "EN", "modules_delete_subtext", "Do you want yo delete this module ?",
            "FR", "modules_delete_subtext", "Confirmez-vous la suppression de ce module ?",
            "EN", "datamarts_delete", "Delete a datamart",
            "FR", "datamarts_delete", "Supprimer un datamart",
            "EN", "datamarts_delete_subtext", "Do you want yo delete this datamart ?",
            "FR", "datamarts_delete_subtext", "Confirmez-vous la suppression de ce datamart ?",
            "EN", "studies_delete", "Delete a study",
            "FR", "studies_delete", "Supprimer une étude",
            "EN", "studies_delete_subtext", "Do you want yo delete this study ?",
            "FR", "studies_delete_subtext", "Confirmez-vous la suppression de cette étude ?",
            "EN", "subsets_delete", "Delete subset",
            "FR", "subsets_delete", "Supprimer un subset",
            "EN", "subsets_delete_subtext", "Do you want yo delete this subset ?",
            "FR", "subsets_delete_subtext", "Confirmez-vous la suppression de ce subset ?",
            "EN", "thesaurus_delete", "Delete thesaurus",
            "FR", "thesaurus_delete", "Supprimer un thésaurus",
            "EN", "thesaurus_delete_subtext", "Do you want yo delete this thesaurus ?",
            "FR", "thesaurus_delete_subtext", "Confirmez-vous la suppression de ce thésaurus ?",
            "EN", "thesaurus_items_delete", "Delete thesaurus item",
            "FR", "thesaurus_items_delete", "Supprimer un item de thésaurus",
            "EN", "thesaurus_items_delete_subtext", "Do you want yo delete this thesaurus item ?",
            "FR", "thesaurus_items_delete_subtext", "Confirmez-vous la suppression de cet item de thésaurus ?",
            "EN", "plugins_delete", "Delete a plugin",
            "FR", "plugins_delete", "Supprimer un plugin",
            "EN", "plugins_delete_subtext", "Do you want yo delete this plugin ?",
            "FR", "plugins_delete_subtext", "Confirmez-vous la suppression de ce plugin ?",
            "EN", "edit_datamart_code", "Edit datamart code",
            "FR", "edit_datamart_code", "Editer le code du datamart",
            "EN", "edit_thesaurus_code", "Edit thesaurus code",
            "FR", "edit_thesaurus_code", "Editer le code du thésaurus",
            "EN", "edit_plugin_code", "Edit plugin code",
            "FR", "edit_plugin_code", "Editer le code du plugin",
            "EN", "edit_subset_code", "Edit subset code",
            "FR", "edit_subset_code", "Editer le code du subset",
            "EN", "provide_valid_name", "Please provide a valid name",
            "FR", "provide_valid_name", "Nom valide requis",
            "EN", "provide_valid_username", "Please provide a valid username",
            "FR", "provide_valid_username", "Pseudo valide requis",
            "EN", "provide_valid_firstname", "Please provide a valid first name",
            "FR", "provide_valid_firstname", "Prénom valide requis",
            "EN", "provide_valid_lastname", "Please provide a valid last name",
            "FR", "provide_valid_lastname", "Nom valide requis",
            "EN", "provide_valid_user_access", "Please choose a user access",
            "FR", "provide_valid_user_access", "Sélectionner un accès",
            "EN", "provide_valid_user_status", "Please choose a status",
            "FR", "provide_valid_user_status", "Sélectionner un statut",
            "EN", "provide_valid_dbname", "Please provide a valid name",
            "FR", "provide_valid_dbname", "Nom valide requis",
            "EN", "provide_valid_description", "Please provide a valid description",
            "FR", "provide_valid_description", "Description valide requise",
            "EN", "provide_data_source", "Please select a data source",
            "FR", "provide_data_source", "Sélectionner une source de données",
            "EN", "provide_valid_user", "Please provide a valid username",
            "FR", "provide_valid_user", "Nom d'utilisateur valide requis",
            "EN", "provide_valid_host", "Please provide a valid host",
            "FR", "provide_valid_host", "Hôte valide requis",
            "EN", "provide_valid_port", "Please provide a valid port (eg : 5432)",
            "FR", "provide_valid_port", "Port valide requis (ex : 5432)",
            "EN", "provide_valid_password", "Please provide a valid password",
            "FR", "provide_valid_password", "Mot de passe valide requis",
            "EN", "name_already_used", "This name is already used",
            "FR", "name_already_used", "Ce nom est déjà utilisé",
            "EN", "username_already_used", "This username is already used",
            "FR", "username_already_used", "Ce pseudo est déjà utilisé",
            "EN", "id", "ID",
            "FR", "id", "ID",
            "EN", "data_source_id", "Data source ID",
            "FR", "data_source_id", "ID source de données",
            "EN", "datamart_id", "Datamart ID",
            "FR", "datamart_id", "ID datamart",
            "EN", "study_id", "Study ID",
            "FR", "study_id", "ID étude",
            "EN", "creator", "Creator",
            "FR", "creator", "Créateur",
            "EN", "datetime", "Date & time",
            "FR", "datetime", "Date & heure",
            "EN", "action", "Action",
            "FR", "action", "Action",
            "EN", "datamart_users_allowed_read", "Grant access to",
            "FR", "datamart_users_allowed_read", "Donner l'accès à",
            "EN", "plugin_users_allowed_read", "Grant access to",
            "FR", "plugin_users_allowed_read", "Donner l'accès à",
            "EN", "study_users_allowed_read", "Grant access to",
            "FR", "study_users_allowed_read", "Donner l'accès à",
            "EN", "show_only_aggregated_data", "Show only aggregated data",
            "FR", "show_only_aggregated_data", "N'autoriser l'accès qu'aux données aggrégées",
            "EN", "modif_names_duplicates", "There are duplicates in the names, please remove duplicates before saving",
            "FR", "modif_names_duplicates", "Certains noms sont utilisés plusieurs fois, retirez-les avant de sauvegarder",
            "EN", "modif_display_order_duplicates", "There are duplicates in display orders, please remove duplicates before saving",
            "FR", "modif_display_order_duplicates", "Certains ordres d'affichage sont utilisés plusieurs fois, retirez-les avant de sauvegarder",
            "EN", "success", "Success",
            "FR", "success", "Succès",
            "EN", "sql_lib", "SQL library",
            "FR", "sql_lib", "Librairie SQL",
            "EN", "table_name", "Table name",
            "FR", "table_name", "Nom de la table",
            "EN", "row_number", "Number of rows",
            "FR", "row_number", "Nombres de lignes",
            "EN", "db_connection_infos_card", "Connection infos",
            "FR", "db_connection_infos_card", "Informations de connexion",
            "EN", "db_datatable_card", "Database tables",
            "FR", "db_datatable_card", "Liste tables de la BDD",
            "EN", "db_request_card", "Request database",
            "FR", "db_request_card", "Requêter la BDD",
            "EN", "db_save_card", "Save database",
            "FR", "db_save_card", "Faire une sauvegarde",
            "EN", "db_restore_card", "Restore database",
            "FR", "db_restore_card", "Restaurer la BDD",
            "EN", "db_save", "Save database",
            "FR", "db_save", "Faire une sauvegarde la BDD",
            "EN", "last_db_save", "Last export",
            "FR", "last_db_save", "Dernière sauvegarde",
            "EN", "last_db_restore", "Last import",
            "FR", "last_db_restore", "Dernière restauration",
            "EN", "db_restore", "Restore database",
            "FR", "db_restore", "Restaurer la BDD",
            "EN", "add_user", "Add a new user",
            "FR", "add_user", "Ajouter utilisateur",
            "EN", "users_delete_data", "Delete data",
            "FR", "users_delete_data", "Supprimer des données",
            "EN", "users_creation_card", "Add new user",
            "FR", "users_creation_card", "Ajouter un utilisateur",
            "EN", "users_management_card", "Users mngmt",
            "FR", "users_management_card", "Gestion utilisateurs",
            "EN", "users_management", "Users management",
            "FR", "users_management", "Gestion des utilisateurs",
            "EN", "users_accesses_creation_card", "Add access",
            "FR", "users_accesses_creation_card", "Ajouter accès",
            "EN", "add_access", "Add an access",
            "FR", "add_access", "Ajouter un accès",
            "EN", "users_accesses_management_card", "Accesses mngmt",
            "FR", "users_accesses_management_card", "Gestion accès",
            "EN", "users_accesses_management", "Accesses management",
            "FR", "users_accesses_management", "Gestion des accès",
            "EN", "users_accesses_options_card", "Accesses opts",
            "FR", "users_accesses_options_card", "Options accès",
            "EN", "users_accesses_options", "Accesses management",
            "FR", "users_accesses_options", "Gestion des accès",
            "EN", "users_statuses_creation_card", "Add status",
            "FR", "users_statuses_creation_card", "Ajouter statut",
            "EN", "add_status", "Add a status",
            "FR", "add_status", "Ajouter un statut",
            "EN", "users_statuses_management_card", "Statuses mngmt",
            "FR", "users_statuses_management_card", "Gestion statuts",
            "EN", "users_statuses_management", "Statuses management",
            "FR", "users_statuses_management", "Gestion des statuts",
            "EN", "user_status_added", "New status added",
            "FR", "user_status_added", "Nouveau statut ajouté",
            "EN", "user_access_added", "New access added",
            "FR", "user_access_added", "Nouvel accès ajouté",
            "EN", "need_create_user_access", "Need to create user accesses and/or user statuses before",
            "FR", "need_create_user_access", "Il faut créer les accès utilisateurs et/ou les statuts utilisateurs avant",
            "EN", "user_added", "New user added",
            "FR", "user_added", "Nouvel utilisateur ajouté",
            "EN", "delete", "Delete",
            "FR", "delete", "Confirmer",
            "EN", "dont_delete", "Don't delete",
            "FR", "dont_delete", "Annuler",
            "EN", "users_delete", "Delete a user",
            "FR", "users_delete", "Supprimer un utilisateur",
            "EN", "users_delete_subtext", "Do you want yo delete this user ?",
            "FR", "users_delete_subtext", "Confirmez-vous la suppression de cet utilisateur ?",
            "EN", "users_statuses_delete", "Delete a status",
            "FR", "users_statuses_delete", "Supprimer un statut",
            "EN", "users_statuses_delete_subtext", "Do you want yo delete this status ?",
            "FR", "users_statuses_delete_subtext", "Confirmez-vous la suppression de ce statut ?",
            "EN", "users_accesses_delete", "Delete an access",
            "FR", "users_accesses_delete", "Supprimer un accès",
            "EN", "users_accesses_delete_subtext", "Do you want yo delete this access ?",
            "FR", "users_accesses_delete_subtext", "Confirmez-vous la suppression de cet accès ?",
            "EN", "user_deleted", "User deleted",
            "FR", "user_deleted", "Utilisateur supprimé",
            "EN", "user_status_deleted", "Status deleted",
            "FR", "user_status_deleted", "Statut supprimé",
            "EN", "user_access_deleted", "Access deleted",
            "FR", "user_access_deleted", "Accès supprimé",
            "EN", "plugin_added", "New plugin added",
            "FR", "plugin_added", "Nouveau plugin ajouté",
            "EN", "plugin_deleted", "Plugin deleted",
            "FR", "plugin_deleted", "Plugin supprimé",
            "EN", "plugins_creation", "Create a new plugin",
            "FR", "plugins_creation", "Créer un nouveau plugin",
            "EN", "plugins_creation_card", "Create a new plugin",
            "FR", "plugins_creation_card", "Créer un nouveau plugin",
            "EN", "plugins_description", "Plugins descriptions",
            "FR", "plugins_description", "Description des plugins",
            "EN", "plugins_description_card", "Plugins descriptions",
            "FR", "plugins_description_card", "Description des plugins",
            "EN", "plugins_management", "Plugins management",
            "FR", "plugins_management", "Gestion des plugins",
            "EN", "plugins_management_card", "Plugins management",
            "FR", "plugins_management_card", "Gestion des plugins",
            "EN", "plugins_datatable_card", "Plugins management",
            "FR", "plugins_datatable_card", "Gestion des plugins",
            "EN", "plugins_code", "Edit code",
            "FR", "plugins_code", "Editer le code d'un plugin",
            "EN", "plugins_edit_code_card", "Edit code",
            "FR", "plugins_edit_code_card", "Editer le code d'un plugin",
            "EN", "plugins_options", "Edit options",
            "FR", "plugins_options", "Options du plugin",
            "EN", "plugins_options_card", "Edit options",
            "FR", "plugins_options_card", "Options du plugin",
            "EN", "help_pages", "Help pages",
            "FR", "help_pages", "Pages d'aide",
            "EN", "module_type", "Module type",
            "FR", "module_type", "Type de module",
            "EN", "modules_creation_card", "New module",
            "FR", "modules_creation_card", "Nouveau module",
            "EN", "modules_families_creation_card", "New module family",
            "FR", "modules_families_creation_card", "Nouveau groupe de modules",
            "EN", "modules_elements_creation_card", "New module element",
            "FR", "modules_elements_creation_card", "Nouvelle figure",
            "EN", "patient_modules_creation_card", "Create a new module",
            "FR", "patient_modules_creation_card", "Créer un nouveau module",
            "EN", "aggregated_modules_creation_card", "Create a new module",
            "FR", "aggregated_modules_creation_card", "Créer un nouveau module",
            "EN", "modules_creation", "Create a new module",
            "FR", "modules_creation", "Créer un nouveau module",
            "EN", "modules_management_card", "Modules mngt",
            "FR", "modules_management_card", "Gestion modules",
            "EN", "modules_families_management_card", "Modules families mngt",
            "FR", "modules_families_management_card", "Gestion groupes de modules",
            "EN", "modules_elements_management_card", "Modules elements mngt",
            "FR", "modules_elements_management_card", "Gestion figures",
            "EN", "modules_families_options_card", "Modules families options",
            "FR", "modules_families_options_card", "Options des groupes de modules",
            "EN", "patient_modules_management_card", "Modules management",
            "FR", "patient_modules_management_card", "Gestion des modules",
            "EN", "aggregated_modules_management_card", "Modules management",
            "FR", "aggregated_modules_management_card", "Gestion des modules",
            "EN", "modules_management", "Modules management",
            "FR", "modules_management", "Gestion des modules",
            "EN", "modules_options_card", "Module options",
            "FR", "modules_options_card", "Options du module",
            "EN", "patient_modules_options_card", "Module options",
            "FR", "patient_modules_options_card", "Options du module",
            "EN", "aggregated_modules_options_card", "Module options",
            "FR", "aggregated_modules_options_card", "Options du module",
            "EN", "modules_options", "Module options",
            "FR", "modules_options", "Options du module",
            "EN", "new_module_added", "New module added",
            "FR", "new_module_added", "Nouveau module ajouté",
            "EN", "req_module_family", "Need to create at least one module family before creating a module",
            "FR", "req_module_family", "Il faut créer au moins une familly de module avant de créer un module",
            "EN", "patient_lvl_modules_delete", "Delete a module",
            "FR", "patient_lvl_modules_delete", "Supprimer un module",
            "EN", "patient_lvl_modules_delete_subtext", "Do you want to delete this module ?",
            "FR", "patient_lvl_modules_delete_subtext", "Confirmez-vous la suppression du module ?",
            "EN", "patient_lvl_module_deleted", "Module deleted",
            "FR", "patient_lvl_module_deleted", "Module supprimé",
            "EN", "aggregated_modules_delete", "Delete a module",
            "FR", "aggregated_modules_delete", "Supprimer un module",
            "EN", "aggregated_modules_delete_subtext", "Do you want to delete this module ?",
            "FR", "aggregated_modules_delete_subtext", "Confirmez-vous la suppression du module ?",
            "EN", "aggregated_module_deleted", "Module deleted",
            "FR", "aggregated_module_deleted", "Module supprimé",
            "EN", "patient_lvl_modules_families_delete", "Delete a module family",
            "FR", "patient_lvl_modules_families_delete", "Supprimer un groupe de modules",
            "EN", "patient_lvl_modules_families_delete_subtext", "Do you want to delete this module family ?",
            "FR", "patient_lvl_modules_families_delete_subtext", "Confirmez-vous la suppression du groupe de modules ?",
            "EN", "patient_lvl_module_family_deleted", "Module family deleted",
            "FR", "patient_lvl_module_family_deleted", "Groupe de modules supprimé",
            "EN", "aggregated_modules_families_delete", "Delete a module family",
            "FR", "aggregated_modules_families_delete", "Supprimer un groupe de modules",
            "EN", "aggregated_modules_families_delete_subtext", "Do you want to delete this module family ?",
            "FR", "aggregated_modules_families_delete_subtext", "Confirmez-vous la suppression du groupe de modules ?",
            "EN", "aggregated_module_family_deleted", "Module family deleted",
            "FR", "aggregated_module_family_deleted", "Groupe de modules supprimé",
            "EN", "patient_lvl_modules_elements_delete", "Delete a module element",
            "FR", "patient_lvl_modules_elements_delete", "Supprimer une figure",
            "EN", "patient_lvl_modules_elements_delete_subtext", "Do you want to delete this module element ?",
            "FR", "patient_lvl_modules_elements_delete_subtext", "Confirmez-vous la suppression de la figure ?",
            "EN", "patient_lvl_module_element_deleted", "Module element deleted",
            "FR", "patient_lvl_module_element_deleted", "Figure supprimée",
            "EN", "aggregated_modules_elements_delete", "Delete a module family element",
            "FR", "aggregated_modules_elements_delete", "Supprimer une figure",
            "EN", "aggregated_modules_elements_delete_subtext", "Do you want to delete this module element ?",
            "FR", "aggregated_modules_elements_delete_subtext", "Confirmez-vous la suppression de la figure ?",
            "EN", "aggregated_module_element_deleted", "Module element deleted",
            "FR", "aggregated_module_element_deleted", "Figure supprimée",
            "EN", "patient_lvl_module_family_options", "Module family options",
            "FR", "patient_lvl_modules_family_options", "Options du groupe de modules",
            "EN", "aggregated_module_family_options", "Module family options",
            "FR", "aggregated_modules_family_options", "Options du groupe de modules",
            "EN", "settings_modules_patient_lvl_module_family_options_users_allowed_read", "Grant access to",
            "FR", "settings_modules_patient_lvl_module_family_options_users_allowed_read", "Donner l'accès à",
            "EN", "settings_modules_aggregated_module_family_options_users_allowed_read", "Grant access to",
            "FR", "settings_modules_aggregated_module_family_options_users_allowed_read", "Donner l'accès à",
            "EN", "none", "None",
            "FR", "none", "Aucun",
            "EN", "thesaurus_id", "Thesaurus ID",
            "FR", "thesaurus_id", "ID du thésaurus",
            "EN", "display_name", "Display name",
            "FR", "display_name", "Nom d'affichage",
            "EN", "category", "Category",
            "FR", "category", "Catégorie",
            "EN", "unit", "Unit",
            "FR", "unit", "Unité",
            "EN", "item_id", "Item ID",
            "FR", "item_id", "ID de l'item",
            "EN", "item_name", "Item name",
            "FR", "item_name", "Nom de l'item",
            "EN", "ui", "UI",
            "FR", "ui", "UI",
            "EN", "server", "Server",
            "FR", "server", "Server",
            "EN", "module_options", "Module options",
            "FR", "module_options", "Options du module",
            "EN", "add_module", "Add a module",
            "FR", "add_module", "Ajouter un module",
            "EN", "add_module_family", "Add a module family",
            "FR", "add_module_family", "Ajouter un groupe de modules",
            "EN", "add_module_element", "Add a module element",
            "FR", "add_module_element", "Ajouter une figure",
            "EN", "datatable_module_elements", "Module elements management",
            "FR", "datatable_module_elements", "Gestion des figures",
            "EN", "DT_previous_page", "Previous",
            "FR", "DT_previous_page", "Précédente",
            "EN", "DT_next_page", "Next",
            "FR", "DT_next_page", "Suivante",
            "EN", "DT_search", "Search : ",
            "FR", "DT_search", "Rechercher : ",
            "EN", "DT_length", "Show _MENU_ entries",
            "FR", "DT_length", "Afficher _MENU_ lignes",
            "EN", "DT_empty", "No data available",
            "FR", "DT_empty", "Pas de données disponibles",
            "EN", "fields_empty", "Some fields are empty",
            "FR", "fields_empty", "Certains champs ne sont pas complétés",
            "EN", "module_element_added", "Module element added",
            "FR", "module_element_added", "Figure ajoutée",
            "EN", "thesaurus_item", "Thesaurus item",
            "FR", "thesaurus_item", "Item du thésaurus",
            "EN", "thesaurus_item_display_name", "Display name",
            "FR", "thesaurus_item_display_name", "Nom d'affichage de l'item",
            "EN", "thesaurus_item_unit", "Item unit",
            "FR", "thesaurus_item_unit", "Unité de l'item",
            "EN", "display_order", "Display order",
            "FR", "display_order", "Ordre d'affichage",
            "EN", "module_element", "Module element",
            "FR", "module_element", "Nom de la figure",
            "EN", "error_run_plugin_ui_code", "Error when running plugin's UI code",
            "FR", "error_run_plugin_ui_code", "Erreur à l'éxécution du code de l'interface utilisateur du plugin",
            "EN", "error_run_plugin_server_code", "Error when running plugin's server code",
            "FR", "error_run_plugin_server_code", "Erreur à l'éxécution du code serveur du plugin",
            "EN", "valuenum", "Numeric value",
            "FR", "valuenum", "Valeur numérique",
            "EN", "value", "Value",
            "FR", "value", "Valeur",
            "EN", "user_side", "User side",
            "FR", "user_side", "En tant qu'utilisateur",
            "EN", "dev_side", "Developper side",
            "FR", "dev_side", "En tant que développeur",
            "EN", "libraries_needed_plugin", "Librairies needed to run this plugin",
            "FR", "libraries_needed_plugin", "Librairies nécessaires pour utiliser ce plugin",
            "EN", "invalid_col_names", "Invalid column names",
            "FR", "invalid_col_names", "Nom de colonnes non valides",
            "EN", "invalid_col_types", "Invalid column types",
            "FR", "invalid_col_types", "Types de colonne non valides",
            "EN", "valid_col_names_are", "Column names are not valid. Valid col names are : ",
            "FR", "valid_col_names_are", "Noms de colonnes non valides. Les noms requis sont : ",
            "EN", "column", "Column",
            "FR", "column", "La colonne",
            "EN", "type_must_be_integer", "type must be integer",
            "FR", "type_must_be_integer", "doit être de type integer",
            "EN", "type_must_be_character", "type must be character",
            "FR", "type_must_be_character", "doit être de type character",
            "EN", "type_must_be_numeric", "type must be numeric",
            "FR", "type_must_be_numeric", "doit être de type numeric",
            "EN", "type_must_be_datetime", "type must be datetime",
            "FR", "type_must_be_datetime", "doit être de type datetime",
            "EN", "error_saving_csv", "Error saving CSV file",
            "FR", "error_saving_csv", "Erreur dans l'enregistrement du fichier CSV",
            "EN", "var_type_not_valid", "Variable 'type' is not valid",
            "FR", "var_type_not_valid", "La variable 'type' n'est pas valide",
            "EN", "error_transforming_tibble", "Error transforming data to tibble",
            "FR", "error_transforming_tibble", "Erreur dans la conversion de la variable au format tibble",
            "EN", "error_loading_csv", "Error loading CSV file",
            "FR", "error_loading_csv", "Erreur lors du chargement du fichier CSV",
            "EN", "no_study_available", "No study available",
            "FR", "no_study_available", "Pas d'étude disponible",
            "EN", "no_subset_available", "No subset available",
            "FR", "no_subset_available", "Pas de subset disponible",
            "EN", "no_patient_available", "No patient available",
            "FR", "no_patient_available", "Pas de patient disponible",
            "EN", "no_stay_available", "No stay available",
            "FR", "no_stay_available", "Pas de séjour disponible",
            "EN", "thesaurus_no_items_to_insert", "There's not any new items to insert in the database",
            "FR", "thesaurus_no_items_to_insert", "Pas de nouvel item à insérer dans la base de données",
            "EN", "error_get_actual_items", "Error with getting actual thesaurus items",
            "FR", "error_get_actual_items", "Erreur lors du chargement des items actuels du thésaurus",
            "EN", "thesaurus_error_append_table", "Error adding new thesaurus items to database table",
            "FR", "thesaurus_error_append_table", "Erreur lors de l'ajout des nouveaux items dans la table du thésaurus",
            "EN", "import_datamart_success", "Datamart(s) imported with success",
            "FR", "import_datamart_success", "Datamart(s) importé(s) avec succès",
            "EN", "import_datamart_success_patients", "Variable patients imported with success",
            "FR", "import_datamart_success_patients", "Variable patients importé avec succès",
            "EN", "import_datamart_success_stays", "Variable stays imported with success",
            "FR", "import_datamart_success_stays", "Variable stays importé avec succès",
            "EN", "import_datamart_success_labs_vitals", "Variable labs_vitals imported with success",
            "FR", "import_datamart_success_labs_vitals", "Variable labs_vitals importé avec succès",
            "EN", "import_datamart_success_text", "Variable text imported with success",
            "FR", "import_datamart_success_text", "Variable text importé avec succès",
            "EN", "import_datamart_success_orders", "Variable orders imported with success",
            "FR", "import_datamart_success_orders", "Variable orders importé avec succès",
            "EN", "import_thesaurus_success", "Thesaurus imported with success",
            "FR", "import_thesaurus_success", "Thesaurus importé avec succès",
            "EN", "dropdown_empty", "At least one dropdown is empty",
            "FR", "dropdown_empty", "Il manque au moins une valeur dans les menus déroulants",
            "EN", "subset_all_patients", "All patients",
            "FR", "subset_all_patients", "Tous les patients",
            "EN", "subset_all_patients_long", "Subset containing all patients",
            "FR", "subset_all_patients_long", "Subset comprenant tous les patients",
            "EN", "subset_included_patients", "Included patients",
            "FR", "subset_included_patients", "Patients inclus",
            "EN", "subset_included_patients_long", "Subset containing only included patients",
            "FR", "subset_included_patients_long", "Subset comprenant seulement les patients inclus",
            "EN", "subset_excluded_patients", "Excluded patients",
            "FR", "subset_excluded_patients", "Patients exclus",
            "EN", "subset_excluded_patients_long", "Subset containing only excluded patients",
            "FR", "subset_excluded_patients_long", "Subset comprenant seulement les patients exclus",
            "EN", "undefined_status", "Undefined",
            "FR", "undefined_status", "Non défini",
            "EN", "included_status", "Included",
            "FR", "included_status", "Inclus",
            "EN", "excluded_status", "Excluded",
            "FR", "excluded_status", "Exclus",
            "EN", "invalid_table_name", "Invalid table name",
            "FR", "invalid_table_name", "Nom de table non valide",
            "EN", "tables_allowed", "Tables allowed",
            "FR", "tables_allowed", "Tables autorisées",
            "EN", "fail_load_code", "Failed loading code",
            "FR", "fail_load_code", "Erreur lors du chargement du code",
            "EN", "fail_load_datamart", "Failed loading datamart",
            "FR", "fail_load_datamart", "Erreur lors du chargement du datamart",
            "EN", "fail_execute_code", "Failed executing code",
            "FR", "fail_execute_code", "Erreur lors de l'éxécution du code",
            "EN", "success_load_patients", "Success loading patients",
            "FR", "success_load_patients", "Chargement de la variable patients avec succès",
            "EN", "success_load_stays", "Success loading stays",
            "FR", "success_load_stays", "Chargement de la variable stays avec succès",
            "EN", "success_load_labs_vitals", "Success loading labs_vitals",
            "FR", "success_load_labs_vitals", "Chargement de la variable labs_vitals avec succès",
            "EN", "success_load_text", "Success loading text",
            "FR", "success_load_text", "Chargement de la variable text avec succès",
            "EN", "success_load_orders", "Success loading orders",
            "FR", "success_load_orders", "Chargement de la variable orders avec succès",
            "EN", "subset_containing_patients_erase_false", "Subset already containing patients. Set erase to TRUE if you want to remove these patients.",
            "FR", "subset_containing_patients_erase_false", "Subset contenant déjà des patients. Mettre la variable erase à TRUE pour les supprimer.",
            "EN", "error_erasing_data", "Error erasing existing data",
            "FR", "error_erasing_data", "Erreur lors de la suppression des données",
            "EN", "error_inserting_data", "Error inserting data in database",
            "FR", "error_inserting_data", "Erreur lors de l'insertion de données dans la BDD",
            "EN", "add_patients_subset_success", "Success adding patients to subset",
            "FR", "add_patients_subset_success", "Insertion de patients dans le subset avec succès",
            "EN", "invalid_subset_id_value", "Invalid subset_id value",
            "FR", "invalid_subset_id_value", "Valeur de subset_id non valide",
            "EN", "invalid_datamart_id_value", "Invalid datamart_id value",
            "FR", "invalid_datamart_id_value", "Valeur de datamart_id non valide",
            "EN", "invalid_thesaurus_id_value", "Invalid thesaurus_id value",
            "FR", "invalid_thesaurus_id_value", "Valeur de thesaurus_id non valide",
            "EN", "error_loading_datamart", "Error loading datamart",
            "FR", "error_loading_datamart", "Erreur lors du chargement du datamart",
            "EN", "visibility", "Visibility",
            "FR", "visibility", "Visibilité",
            "EN", "dev_only", "Developpers only",
            "FR", "dev_only", "Développeurs uniquemement",
            "EN", "public_access", "Public access",
            "FR", "public_access", "Accès public",
            "EN", "deleted_user", "Deleted user",
            "FR", "deleted_user", "Utilisateur supprimé",
            "EN", "r_console", "R console",
            "FR", "r_console", "Console R",
            "EN", "r_console_edit_code_card", "Edit code",
            "FR", "r_console_edit_code_card", "Editer le code",
            "EN", "creating_cache", "First load of thesaurus items : creating cache, may take a few seconds",
            "FR", "creating_cache", "Premier chargement des items de ce thésaurus : création du cache, peut prendre quelques secondes",
            "EN", "age", "Age",
            "FR", "age", "Age",
            "EN", "gender", "Gender",
            "FR", "gender", "Sexe",
            "EN", "years", "years",
            "FR", "years", "ans",
            "EN", "patient_status", "Patient status",
            "FR", "patient_status", "Statut du patient",
            "EN", "from", "From",
            "FR", "from", "Du",
            "EN", "to", "To",
            "FR", "to", "Au",
            "EN", "num_patients", "Nb of patients",
            "FR", "num_patients", "Nb de patients",
            "EN", "num_rows", "Nb of rows",
            "FR", "num_rows", "Nb de lignes",
            "EN", "show_only_used_items", "Show only used items in this datamart",
            "FR", "show_only_used_items", "N'afficher que les items utilisés dans ce datamart",
            "EN", "show_only_used_items_patient", "Show only used items by this patient",
            "FR", "show_only_used_items_patient", "N'afficher que les items utilisés par ce patient",
            "EN", "no_modules_to_show", "There are no modules set for this study. Configure modules in parameters.",
            "FR", "no_modules_to_show", "Il n'y a pas de module configuré pour cette étude. Configurer les modules dans les paramètres.",
            "EN", "no_thesaurus_item_to_show", "No thesaurus items to show in this module",
            "FR", "no_thesaurus_item_to_show", "Pas d'items de thésaurus à afficher pour ce module",
            "EN", "select_all", "Select all",
            "FR", "select_all", "Tout sélectionner",
            "EN", "unselect_all", "Unselect all",
            "FR", "unselect_all", "Tout déselectionner",
            "EN", "all_users", "All users",
            "FR", "all_users", "Tous les utilisateurs",
            "EN", "only_me", "Only me",
            "FR", "only_me", "Uniquement moi",
            "EN", "patient_already_in_subset", "Patient already in this subset",
            "FR", "patient_already_in_subset", "Patient déjà dans ce subset",
            "EN", "error_removing_patients_from_subset", "Error removing patients from subset",
            "FR", "error_removing_patients_from_subset", "Erreur lors de la suppression des patients du subset",
            "EN", "thesaurus_items_empty", "Choose at least one thesaurus item",
            "FR", "thesaurus_items_empty", "Choisir au moins un item du thésaurus",
            "EN", "exclusion_reason", "Exclusion reason",
            "FR", "exclusion_reason", "Motif d'exclusion",
            "EN", "everybody", "Everybody",
            "FR", "everybody", "Tout le monde",
            "EN", "people_picker", "Choose users",
            "FR", "people_picker", "Choisir les utilisateurs",
            "EN", "data_sources_see_all_data", "See all data",
            "FR", "data_sources_see_all_data", "Accès à toutes les données",
            "EN", "data_sources_delete_data", "Delete data",
            "FR", "data_sources_delete_data", "Supprimer des données",
            "EN", "datamarts_see_all_data", "See all data",
            "FR", "datamarts_see_all_data", "Accès à toutes les données",
            "EN", "datamarts_delete_data", "Delete data",
            "FR", "datamarts_delete_data", "Supprimer des données",
            "EN", "studies_see_all_data", "See all data",
            "FR", "studies_see_all_data", "Accès à toutes les données",
            "EN", "studies_delete_data", "Delete data",
            "FR", "studies_delete_data", "Supprimer des données",
            "EN", "subsets_see_all_data", "See all data",
            "FR", "subsets_see_all_data", "Accès à toutes les données",
            "EN", "subsets_delete_data", "Delete data",
            "FR", "subsets_delete_data", "Supprimer des données",
            "EN", "thesaurus_see_all_data", "See all data",
            "FR", "thesaurus_see_all_data", "Accès à toutes les données",
            "EN", "thesaurus_delete_data", "Delete data",
            "FR", "thesaurus_delete_data", "Supprimer des données",
            "EN", "plugins_see_all_data", "See all data",
            "FR", "plugins_see_all_data", "Accès à toutes les données",
            "EN", "plugins_delete_data", "Delete data",
            "FR", "plugins_delete_data", "Supprimer des données",
            "EN", "never", "Never",
            "FR", "never", "Jamais"
            ) -> data
    # readr::write_csv(data, needed_file)
  # }
  # if (file.exists(needed_file)) vroom::vroom(file = needed_file, col_types = c("")) -> data
  data
}
