#' Translates a word
#'
#' @param language A two-letters or three-letters character indicating the requested language
#' @param words A tibble containing the translations
#' @description Translates a reference word to the requested language
#'
#' @return Returns the translated word (character)
#' @examples
#' words <- dplyr::tribble(~language, ~reference_word, ~translated_word,
#' "FR", "Settings", "Parametres",
#' "IT", "Settings", "Impostazioni")
#' 
#' translate("ESP", words, "Settings")
#' translate("FR", words, "Settings")

translate <- function(language, reference_word){
  words <- get_translations()
  if (nchar(language) %not_in% c(2, 3)) stop("Input 'language' has less than 2 or more than 3 characters")
  if (!is.data.frame(words)) stop("Input 'words' is not a dataframe")
  if (!is.character(reference_word) | nchar(reference_word) == 0) stop("Input 'reference word' is not a character or is of length 0")
  words %>%
    dplyr::filter(language == !!language, reference_word == !!reference_word) %>%
    dplyr::pull(translated_word)
}

#' Create a tibble with translations
#'@noRd
#'

get_translations <- function(){
  needed_file <- "./data/translations.csv"
  # if (!file.exists(needed_file)){
    dplyr::tribble(~language, ~reference_word, ~translated_word,
            "EN", "home", "Home",
            "FR", "home", "Accueil",
            "EN", "patient_level_data", "Patient-level data",
            "FR", "patient_level_data", "Données individuelles",
            "EN", "aggregated_data", "Aggregated data",
            "FR", "aggregated_data", "Données agrégées",
            "EN", "settings", "Settings",
            "FR", "settings", "Paramètres",
            "EN", "help", "Help",
            "FR", "help", "Aide",
            "EN", "datamart", "Datamart",
            "FR", "datamart", "Datamart",
            "EN", "datamarts", "Datamarts",
            "FR", "datamarts", "Datamarts",
            "EN", "datamarts_create", "Create a datamart",
            "FR", "datamarts_create", "Créer un datamart",
            "EN", "datamarts_management", "Datamarts management",
            "FR", "datamarts_management", "Gestion des datamarts",
            "EN", "datamarts_access", "Datamarts access",
            "FR", "datamarts_access", "Accès aux datamarts",
            "EN", "datamart_options", "Datamart options",
            "FR", "datamart_options", "Réglages du datamart",
            "EN", "datamart_access_choice", "Datamart",
            "FR", "datamart_access_choice", "Datamart",
            "EN", "datamart_access_people", "Grant access to",
            "FR", "datamart_access_people", "Permettre l'accès à",
            "EN", "datamarts_studies", "Datamarts & studies",
            "FR", "datamarts_studies", "Datamarts & études",
            "EN", "study_accesses", "Studies accesses",
            "FR", "study_accesses", "Accès aux études",
            "EN", "studies_access_choice", "Study",
            "FR", "studies_access_choice", "Etude",
            "EN", "studies_access_people", "Grant access to",
            "FR", "studies_access_people", "Permettre l'accès à",
            "EN", "study_options", "Study options",
            "FR", "study_options", "Réglages de l'étude",
            "EN", "studies_management_choice", "Study",
            "FR", "studies_management_choice", "Etude",
            "EN", "thesaurus_options", "Thesaurus options",
            "FR", "thesaurus_options", "Réglages du thésaurus",
            "EN", "patient_lvl_module_family", "Patient-level data module family",
            "FR", "patient_lvl_module_family", "Données individuelles - groupe de modules",
            "EN", "aggregated_module_family", "Aggregated data module family",
            "FR", "aggregated_module_family", "Données agrégées - groupe de modules",
            "EN", "patient_lvl_module_family_id", "Patient-lvl data module family ID",
            "FR", "patient_lvl_module_family_id", "Données indiv. - ID groupe de modules",
            "EN", "aggregated_module_family_id", "Aggregated data module family ID",
            "FR", "aggregated_module_family_id", "Données agg. - ID groupe de modules",
            "EN", "study", "Study",
            "FR", "study", "Etude",
            "EN", "studies", "Studies",
            "FR", "studies", "Etudes",
            "EN", "subset", "Subset",
            "FR", "subset", "Subset",
            "EN", "subsets", "Subsets",
            "FR", "subsets", "Subsets",
            "EN", "thesaurus", "Thesaurus",
            "FR", "thesaurus", "Thesaurus",
            "EN", "patient", "Patient",
            "FR", "patient", "Patient",
            "EN", "stay", "Stay",
            "FR", "stay", "Séjour",
            "EN", "general", "General",
            "FR", "general", "Général",
            "EN", "general_settings", "General settings",
            "FR", "general_settings", "Paramètres généraux",
            "EN", "data_management", "Data management",
            "FR", "data_management", "Gestion des données",
            "EN", "data_sources", "Data sources",
            "FR", "data_sources", "Sources de données",
            "EN", "data_source", "Data source",
            "FR", "data_source", "Source de données",
            "EN", "create_data_source", "Create a data source",
            "FR", "create_data_source", "Créer une source de données",
            "EN", "create_datamart", "Create a datamart",
            "FR", "create_datamart", "Créer un datamart",
            "EN", "create_study", "Create a study",
            "FR", "create_study", "Créer une étude",
            "EN", "create_subset", "Create a subset",
            "FR", "create_subset", "Créer un subset",
            "EN", "create_thesaurus", "Create a thesaurus",
            "FR", "create_thesaurus", "Créer un thésaurus",
            "EN", "name", "Name",
            "FR", "name", "Nom",
            "EN", "description", "Description",
            "FR", "description", "Description",
            "EN", "language", "Language",
            "FR", "language", "Langue",
            "EN", "save", "Save",
            "FR", "save", "Sauvegarder",
            "EN", "edit_save", "Save",
            "FR", "edit_save", "Sauvegarder",
            "EN", "execute_code", "Run code",
            "FR", "execute_code", "Exécuter",
            "EN", "datatable_save", "Save",
            "FR", "datatable_save", "Sauvegarder",
            "EN", "appearance", "Appearance",
            "FR", "appearance", "Apparence",
            "EN", "my_account", "My account",
            "FR", "my_account", "Mon compte",
            "EN", "page_type", "Page type",
            "FR", "page_type", "Type de page",
            "EN", "modules_plugins", "Modules & plugins",
            "FR", "modules_plugins", "Modules & plugins",
            "EN", "plugins", "Plugins",
            "FR", "plugins", "Plugins",
            "EN", "plugin", "Plugin",
            "FR", "plugin", "Plugin",
            "EN", "modules_patient_lvl", "Modules patient-level data",
            "FR", "modules_patient_lvl", "Modules données individuelles",
            "EN", "modules_aggregated", "Modules aggregated data",
            "FR", "modules_aggregated", "Modules données agrégées",
            "EN", "dev_mode", "Developper mode",
            "FR", "dev_mode", "Mode développeur",
            "EN", "search", "Search",
            "FR", "search", "Rechercher",
            "EN", "choices", "Choices",
            "FR", "choices", "Choix",
            "EN", "code", "Code",
            "FR", "code", "Code",
            "EN", "page_theme", "Theme",
            "FR", "page_theme", "Thème",
            "EN", "messages", "Messages",
            "FR", "messages", "Messages",
            "EN", "disconnect", "Disconnect",
            "FR", "disconnect", "Déconnexion",
            "EN", "users", "Users",
            "FR", "users", "Utilisateurs",
            "EN", "log", "Log",
            "FR", "log", "Historique",
            "EN", "app_db", "App database",
            "FR", "app_db", "BDD de l'application",
            "EN", "connection_infos", "Connection informations",
            "FR", "connection_infos", "Informations de connexion",
            "EN", "app_db_request", "Request database",
            "FR", "app_db_request", "Requêter la BDD",
            "EN", "request", "Request",
            "FR", "request", "Requêter",
            "EN", "app_db_tables", "Database tables",
            "FR", "app_db_tables", "Tables de la BDD",
            "EN", "db_connexion_type", "Connexion type",
            "FR", "db_connexion_type", "Type de connexion",
            "EN", "local", "Local",
            "FR", "local", "Locale",
            "EN", "distant", "Distant",
            "FR", "distant", "Distante",
            "EN", "dbname", "Database name",
            "FR", "dbname", "Nom de la BDD",
            "EN", "host", "Host",
            "FR", "host", "Hôte",
            "EN", "port", "Port",
            "FR", "port", "Port",
            "EN", "user", "User",
            "FR", "user", "Utilisateur",
            "EN", "password", "Password",
            "FR", "password", "Password",
            "EN", "old_password", "Old password",
            "FR", "old_password", "Ancien mot de passe",
            "EN", "new_password", "New password",
            "FR", "new_password", "Nouveau mot de passe",
            "EN", "username", "Username",
            "FR", "username", "Pseudo",
            "EN", "create_user", "Create a new user",
            "FR", "create_user", "Créer un nouvel utilisateur",
            "EN", "firstname", "First name",
            "FR", "firstname", "Prénom",
            "EN", "lastname", "Last name",
            "FR", "lastname", "Nom",
            "EN", "add", "Add",
            "FR", "add", "Ajouter",
            "EN", "test_connection", "Test connection",
            "FR", "test_connection", "Tester la connexion",
            "EN", "user_access", "User access",
            "FR", "user_access", "Droits d'accès",
            "EN", "user_status", "User status",
            "FR", "user_status", "Statut de l'utilisateur",
            "EN", "user_management", "User management",
            "FR", "user_management", "Gestion des utilisateurs",
            "EN", "get_started", "Get started",
            "FR", "get_started", "Mise en place",
            "EN", "data_sources_create", "Create a data source",
            "FR", "data_sources_create", "Créer une source de données",
            "EN", "data_sources_management", "Data sources management",
            "FR", "data_sources_management", "Gestion des sources de données",
            "EN", "studies_create", "Create a study",
            "FR", "studies_create", "Créer une étude",
            "EN", "studies_management", "Studies management",
            "FR", "studies_management", "Gestion des études",
            "EN", "subsets_create", "Create subset",
            "FR", "subsets_create", "Créer un subset",
            "EN", "subsets_management", "Subsets management",
            "FR", "subsets_management", "Gestion des subsets",
            "EN", "thesaurus_create", "Create a thesaurus",
            "FR", "thesaurus_create", "Créer un thésaurus",
            "EN", "thesaurus_management", "Thesaurus management",
            "FR", "thesaurus_management", "Gestion des thésaurus",
            "EN", "thesaurus_management_card", "Thesaurus mngmt",
            "FR", "thesaurus_management_card", "Gestion des thésaurus",
            "EN", "thesaurus_items", "Items",
            "FR", "thesaurus_items", "Items",
            "EN", "thesaurus_items_management_card", "Items mngmt",
            "FR", "thesaurus_items_management_card", "Items des thésaurus",
            "EN", "thesaurus_items_management", "Items management",
            "FR", "thesaurus_items_management", "Gestion des items",
            "EN", "matching_people", "Matching people",
            "FR", "matching_people", "Personnes correspondant",
            "EN", "no_results_found", "No results found",
            "FR", "no_results_found", "Pas de résultats",
            "EN", "module", "Module",
            "FR", "module", "Module",
            "EN", "modules", "Modules",
            "FR", "modules", "Modules",
            "EN", "module_name", "Name of the module",
            "FR", "module_name", "Nom du module",
            "EN", "module_parent", "Parent module",
            "FR", "module_parent", "Est sous le module",
            "EN", "module_family", "Module family",
            "FR", "module_family", "Appartient au groupe de modules",
            "EN", "module_families", "Module families",
            "FR", "module_families", "Familles de modules",
            "EN", "module_access_type", "Grant access",
            "FR", "module_access_type", "Permettre l'accès",
            "EN", "module_access_people", "Grant access to",
            "FR", "module_access_people", "Donner l'accès à",
            "EN", "parent_module_is_itself", "A module can't be its own parent",
            "FR", "parent_module_is_itself", "Un module ne peut être son propre parent",
            "EN", "log_filters", "Log filters",
            "FR", "log_filters", "Filtrer l'historique",
            "EN", "log_details", "Log details",
            "FR", "log_details", "Détails de l'historique",
            "EN", "log_filter_type", "Filter log of",
            "FR", "log_filter_type", "Montrer l'historique de",
            "EN", "log_filter_people", "Users",
            "FR", "log_filter_people", "Utilisateurs",
            "EN", "modif_saved", "Modifications saved",
            "FR", "modif_saved", "Modifications enregistrées",
            "EN", "data_source_deleted", "Data source deleted",
            "FR", "data_source_deleted", "Source de données supprimée",
            "EN", "datamart_deleted", "Datamart deleted",
            "FR", "datamart_deleted", "Datamart supprimé",
            "EN", "study_deleted", "Study deleted",
            "FR", "study_deleted", "Etude",
            "EN", "subset_deleted", "Subset deleted",
            "FR", "subset_deleted", "Subset supprimé",
            "EN", "thesaurus_deleted", "Thesaurus deleted",
            "FR", "thesaurus_deleted", "Thésaurus supprimé",
            "EN", "thesaurus_item_deleted", "Thesaurus item deleted",
            "FR", "thesaurus_item_deleted", "Item de thésaurus supprimé",
            "EN", "data_source_added", "Data source created",
            "FR", "data_source_added", "Source de données créee",
            "EN", "datamart_added", "Datamart created",
            "FR", "datamart_added", "Datamart crée",
            "EN", "study_added", "Study created",
            "FR", "study_added", "Etude créée",
            "EN", "subset_added", "Subset created",
            "FR", "subset_added", "Subset crée",
            "EN", "thesaurus_added", "Thesaurus created",
            "FR", "thesaurus_added", "Thésaurus crée",
            "EN", "data_sources_delete", "Delete a data source",
            "FR", "data_sources_delete", "Supprimer une source de donnée",
            "EN", "data_sources_delete_subtext", "Do you want yo delete this data source ?",
            "FR", "data_sources_delete_subtext", "Confirmez-vous la suppression de cette source de données ?",
            "EN", "datamarts_delete", "Delete a datamart",
            "FR", "datamarts_delete", "Supprimer un datamart",
            "EN", "datamarts_delete_subtext", "Do you want yo delete this datamart ?",
            "FR", "datamarts_delete_subtext", "Confirmez-vous la suppression de ce datamart ?",
            "EN", "studies_delete", "Delete a study",
            "FR", "studies_delete", "Supprimer une étude",
            "EN", "studies_delete_subtext", "Do you want yo delete this study ?",
            "FR", "studies_delete_subtext", "Confirmez-vous la suppression de cette étude ?",
            "EN", "subsets_delete", "Delete subset",
            "FR", "subsets_delete", "Supprimer un subset",
            "EN", "subsets_delete_subtext", "Do you want yo delete this subset ?",
            "FR", "subsets_delete_subtext", "Confirmez-vous la suppression de ce subset ?",
            "EN", "thesaurus_delete", "Delete thesaurus",
            "FR", "thesaurus_delete", "Supprimer un thésaurus",
            "EN", "thesaurus_delete_subtext", "Do you want yo delete this thesaurus ?",
            "FR", "thesaurus_delete_subtext", "Confirmez-vous la suppression de ce thésaurus ?",
            "EN", "thesaurus_item_delete", "Delete thesaurus item",
            "FR", "thesaurus_item_delete", "Supprimer un item de thésaurus",
            "EN", "thesaurus_item_delete_subtext", "Do you want yo delete this thesaurus item ?",
            "FR", "thesaurus_item_delete_subtext", "Confirmez-vous la suppression de cet item de thésaurus ?",
            "EN", "plugins_delete", "Delete a plugin",
            "FR", "plugins_delete", "Supprimer un plugin",
            "EN", "plugins_delete_subtext", "Do you want yo delete this plugin ?",
            "FR", "plugins_delete_subtext", "Confirmez-vous la suppression de ce plugin ?",
            "EN", "edit_datamart_code", "Edit datamart code",
            "FR", "edit_datamart_code", "Editer le code du datamart",
            "EN", "edit_thesaurus_code", "Edit thesaurus code",
            "FR", "edit_thesaurus_code", "Editer le code du thésaurus",
            "EN", "edit_plugin_code", "Edit plugin code",
            "FR", "edit_plugin_code", "Editer le code du plugin",
            "EN", "provide_valid_name", "Please provide a valid name",
            "FR", "provide_valid_name", "Nom valide requis",
            "EN", "provide_valid_username", "Please provide a valid username",
            "FR", "provide_valid_username", "Pseudo valide requis",
            "EN", "provide_valid_firstname", "Please provide a valid first name",
            "FR", "provide_valid_firstname", "Prénom valide requis",
            "EN", "provide_valid_lastname", "Please provide a valid last name",
            "FR", "provide_valid_lastname", "Nom valide requis",
            "EN", "provide_valid_user_access", "Please choose a user access",
            "FR", "provide_valid_user_access", "Sélectionner un accès",
            "EN", "provide_valid_user_status", "Please choose a status",
            "FR", "provide_valid_user_status", "Sélectionner un statut",
            "EN", "provide_valid_dbname", "Please provide a valid name",
            "FR", "provide_valid_dbname", "Nom valide requis",
            "EN", "provide_valid_description", "Please provide a valid description",
            "FR", "provide_valid_description", "Description valide requise",
            "EN", "provide_data_source", "Please select a data source",
            "FR", "provide_data_source", "Sélectionner une source de données",
            "EN", "provide_valid_user", "Please provide a valid username",
            "FR", "provide_valid_user", "Nom d'utilisateur valide requis",
            "EN", "provide_valid_host", "Please provide a valid host",
            "FR", "provide_valid_host", "Hôte valide requis",
            "EN", "provide_valid_port", "Please provide a valid port (eg : 5432)",
            "FR", "provide_valid_port", "Port valide requis (ex : 5432)",
            "EN", "provide_valid_password", "Please provide a valid password",
            "FR", "provide_valid_password", "Password valide requis",
            "EN", "name_already_used", "This name is already used",
            "FR", "name_already_used", "Ce nom est déjà utilisé",
            "EN", "username_already_used", "This username is already used",
            "FR", "username_already_used", "Ce pseudo est déjà utilisé",
            "EN", "id", "ID",
            "FR", "id", "ID",
            "EN", "data_source_id", "Data source ID",
            "FR", "data_source_id", "ID source de données",
            "EN", "datamart_id", "Datamart ID",
            "FR", "datamart_id", "ID datamart",
            "EN", "study_id", "Study ID",
            "FR", "study_id", "ID étude",
            "EN", "creator", "Creator",
            "FR", "creator", "Créateur",
            "EN", "datetime", "Date & time",
            "FR", "datetime", "Date & heure",
            "EN", "action", "Action",
            "FR", "action", "Action",
            "EN", "datamart_users_allowed_read", "Grant access to",
            "FR", "datamart_users_allowed_read", "Donner l'accès à",
            "EN", "study_users_allowed_read", "Grant access to",
            "FR", "study_users_allowed_read", "Donner l'accès à",
            "EN", "show_only_aggregated_data", "Show only aggregated data",
            "FR", "show_only_aggregated_data", "N'autoriser l'accès qu'aux données aggrégées",
            "EN", "modif_names_duplicates", "There are duplicates in the names, please remove these before saving",
            "FR", "modif_names_duplicates", "Certains noms sont utilisés plusieurs fois, les retirer avant de sauvegarder",
            "EN", "success", "Success",
            "FR", "success", "Succès",
            "EN", "sql_lib", "SQL library",
            "FR", "sql_lib", "Librairie SQL",
            "EN", "table_name", "Table name",
            "FR", "table_name", "Nom de la table",
            "EN", "row_number", "Number of rows",
            "FR", "row_number", "Nombres de lignes",
            "EN", "db_connection_infos_card", "Connection infos",
            "FR", "db_connection_infos_card", "Informations de connexion",
            "EN", "db_datatable_card", "Database tables",
            "FR", "db_datatable_card", "Liste tables de la BDD",
            "EN", "db_request_card", "Request database",
            "FR", "db_request_card", "Requêter la BDD",
            "EN", "db_save_card", "Save database",
            "FR", "db_save_card", "Faire une sauvegarde",
            "EN", "db_restore_card", "Restore database",
            "FR", "db_restore_card", "Restaurer la BDD",
            "EN", "db_save", "Save database",
            "FR", "db_save", "Faire une sauvegarde la BDD",
            "EN", "db_restore", "Restore database",
            "FR", "db_restore", "Restaurer la BDD",
            "EN", "add_user_card", "Add a new user",
            "FR", "add_user_card", "Ajouter utilisateur",
            "EN", "add_user", "Add a new user",
            "FR", "add_user", "Ajouter un utilisateur",
            "EN", "users_management_card", "Users mngmt",
            "FR", "users_management_card", "Gestion utilisateurs",
            "EN", "users_management", "Users management",
            "FR", "users_management", "Gestion des utilisateurs",
            "EN", "add_access_card", "Add an access",
            "FR", "add_access_card", "Ajouter accès",
            "EN", "add_access", "Add an access",
            "FR", "add_access", "Ajouter un accès",
            "EN", "accesses_management_card", "Accesses mngmt",
            "FR", "accesses_management_card", "Gestion accès",
            "EN", "accesses_management", "Accesses management",
            "FR", "accesses management", "Gestion des accès",
            "EN", "add_status_card", "Add a status",
            "FR", "add_status_card", "Ajouter statut",
            "EN", "add_status", "Add a status",
            "FR", "add_status", "Ajouter un statut",
            "EN", "statuses_management_card", "Statuses mngmt",
            "FR", "statuses_management_card", "Gestion statuts",
            "EN", "statuses_management", "Statuses management",
            "FR", "statuses_management", "Gestion des statuts",
            "EN", "status_added", "New status added",
            "FR", "status_added", "Nouveau statut ajouté",
            "EN", "access_added", "New access added",
            "FR", "access_added", "Nouvel accès ajouté",
            "EN", "need_create_user_access", "Need to create user accesses and/or user statuses before",
            "FR", "need_create_user_access", "Il faut créer les accès utilisateurs et/ou les statuts utilisateurs avant",
            "EN", "new_user_added", "New user added",
            "FR", "new_user_added", "Nouvel utilisateur ajouté",
            "EN", "delete", "Delete",
            "FR", "delete", "Confirmer",
            "EN", "dont_delete", "Don't delete",
            "FR", "dont_delete", "Annuler",
            "EN", "users_users_delete", "Delete a user",
            "FR", "users_users_delete", "Supprimer un utilisateur",
            "EN", "users_users_delete_subtext", "Do you want yo delete this user ?",
            "FR", "users_users_delete_subtext", "Confirmez-vous la suppression de cet utilisateur ?",
            "EN", "users_statuses_delete", "Delete a status",
            "FR", "users_statuses_delete", "Supprimer un statut",
            "EN", "users_statuses_delete_subtext", "Do you want yo delete this status ?",
            "FR", "users_statuses_delete_subtext", "Confirmez-vous la suppression de ce statut ?",
            "EN", "user_deleted", "User deleted",
            "FR", "user_deleted", "Utilisateur supprimé",
            "EN", "status_deleted", "Status deleted",
            "FR", "status_deleted", "Statut supprimé",
            "EN", "plugin_deleted", "Plugin deleted",
            "FR", "plugin_deleted", "Plugin supprimé",
            "EN", "plugins_creation", "Create a new plugin",
            "FR", "plugins_creation", "Créer un nouveau plugin",
            "EN", "plugins_creation_card", "Create a new plugin",
            "FR", "plugins_creation_card", "Créer un nouveau plugin",
            "EN", "plugins_description", "Plugins descriptions",
            "FR", "plugins_description", "Description des plugins",
            "EN", "plugins_description_card", "Plugins descriptions",
            "FR", "plugins_description_card", "Description des plugins",
            "EN", "plugins_management", "Plugins management",
            "FR", "plugins_management", "Gestion des plugins",
            "EN", "plugins_management_card", "Plugins management",
            "FR", "plugins_management_card", "Gestion des plugins",
            "EN", "plugins_code", "Edit code",
            "FR", "plugins_code", "Editer le code d'un plugin",
            "EN", "plugins_edit_code_card", "Edit code",
            "FR", "plugins_edit_code_card", "Editer le code d'un plugin",
            "EN", "help_pages", "Help pages",
            "FR", "help_pages", "Pages d'aide",
            "EN", "new_plugin_added", "New plugin added",
            "FR", "new_plugin_added", "Nouveau plugin ajouté",
            "EN", "module_type", "Module type",
            "FR", "module_type", "Type de module",
            "EN", "modules_creation_card", "Create a new module",
            "FR", "modules_creation_card", "Créer un nouveau module",
            "EN", "modules_creation", "Create a new module",
            "FR", "modules_creation", "Créer un nouveau module",
            "EN", "modules_management_card", "Modules management",
            "FR", "modules_management_card", "Gestion des modules",
            "EN", "modules_management", "Modules management",
            "FR", "modules_management", "Gestion des modules",
            "EN", "modules_options_card", "Module options",
            "FR", "modules_options_card", "Options du module",
            "EN", "modules_options", "Module options",
            "FR", "modules_options", "Options du module",
            "EN", "new_module_added", "New module added",
            "FR", "new_module_added", "Nouveau module ajouté",
            "EN", "req_module_family", "Need to create at least one module family before creating a module",
            "FR", "req_module_family", "Il faut créer au moins une familly de module avant de créer un module",
            "EN", "modules_module_delete", "Delete a module",
            "FR", "modules_module_delete", "Supprimer un module",
            "EN", "modules_module_delete_subtext", "Do you want to delete this module ?",
            "FR", "modules_module_delete_subtext", "Confirmez-vous la suppression du module ?",
            "EN", "modules_module_deleted", "Module deleted",
            "FR", "modules_module_deleted", "Module supprimé",
            "EN", "modules_family_delete", "Delete a module family",
            "FR", "modules_family_delete", "Supprimer une famille de modules",
            "EN", "modules_family_delete_subtext", "Do you want to delete this module family ?",
            "FR", "modules_family_delete_subtext", "Confirmez-vous la suppression de la famille de modules ?",
            "EN", "modules_family_deleted", "Module famile deleted",
            "FR", "modules_family_deleted", "Famille de modules supprimée",
            "EN", "none", "None",
            "FR", "none", "Aucun",
            "EN", "thesaurus_id", "Thesaurus ID",
            "FR", "thesaurus_id", "ID du thésaurus",
            "EN", "display_name", "Display name",
            "FR", "display_name", "Nom d'affichage",
            "EN", "category", "Category",
            "FR", "category", "Catégorie",
            "EN", "unit", "Unit",
            "FR", "unit", "Unité",
            "EN", "item_id", "Item ID",
            "FR", "item_id", "ID de l'item",
            "EN", "ui", "UI",
            "FR", "ui", "UI",
            "EN", "server", "Server",
            "FR", "server", "Server",
            "EN", "module_options", "Module options",
            "FR", "module_options", "Options du module",
            "EN", "add_module_element", "Add a module element",
            "FR", "add_module_element", "Ajouter une figure",
            "EN", "datatable_module_elements", "Module elements management",
            "FR", "datatable_module_elements", "Gestion des figures",
            "EN", "DT_previous_page", "Previous",
            "FR", "DT_previous_page", "Précédente",
            "EN", "DT_next_page", "Next",
            "FR", "DT_next_page", "Suivante",
            "EN", "DT_search", "Search : ",
            "FR", "DT_search", "Rechercher : ",
            "EN", "DT_length", "Show _MENU_ entries",
            "FR", "DT_length", "Afficher _MENU_ lignes",
            "EN", "fields_empty", "Some fields are empty",
            "FR", "fields_empty", "Certains champs ne sont pas complétés",
            "EN", "module_element_added", "Module element added",
            "FR", "module_element_added", "Figure ajoutée",
            "EN", "thesaurus_item", "Thesaurus item",
            "FR", "thesaurus_item", "Item du thésaurus",
            "EN", "thesaurus_item_display_name", "Display name",
            "FR", "thesaurus_item_display_name", "Nom d'affichage de l'item",
            "EN", "thesaurus_item_unit", "Item unit",
            "FR", "thesaurus_item_unit", "Unité de l'item",
            "EN", "display_order", "Display order",
            "FR", "display_order", "Order d'affichage",
            "EN", "module_element", "Module element",
            "FR", "module_element", "Nom de la figure",
            "EN", "error_run_plugin_ui_code", "Error when running plugin's UI code",
            "FR", "error_run_plugin_ui_code", "Erreur à l'éxécution du code de l'interface utilisateur du plugin",
            "EN", "error_run_plugin_server_code", "Error when running plugin's server code",
            "FR", "error_run_plugin_server_code", "Erreur à l'éxécution du code serveur du plugin"
            ) -> data
    # readr::write_csv(data, needed_file)
  # }
  # if (file.exists(needed_file)) vroom::vroom(file = needed_file, col_types = c("")) -> data
  data
}